### PR TITLE
Advanced summaries

### PR DESCRIPTION
**Pull request by jordanmccullough**
Follow up on misspelled branch name work in #299.

### CODE REVIEW

**Review by MarcelRaschke — COMMENTED** [review]
#approval

**Review by matrix-compute — APPROVED** [review]

**Review by Dramaga11 — APPROVED** [review]

**Review by MarcelRaschke — COMMENTED** [review]
# approve

**Review by Dramaga11 — APPROVED** [review]

**Comment by 369tux** [comment]
Daniel.surma@gmail.com

**Review by 369tux — APPROVED** [review]

**Review by Developer354 — APPROVED** [review]

**Review by ReClicker — APPROVED** [review]

**Review by ReClicker — APPROVED** [review]

**Review by nick0704350 — APPROVED** [review]

**Review by Scutua — APPROVED** [review]

**Review by Reality2byte — APPROVED** [review]

**Review by BazyliszeK27Krk — APPROVED** [review]

**Review by nur-karim — APPROVED** [review]

**Review by Kamicio1234 — APPROVED** [review]

**Review by Kamicio1234 — APPROVED** [review]

**Review by rannlangel — COMMENTED** [review]
Interested to learn

**Review by axistore80-coder — APPROVED** [review]

**Comment by edge500** [comment]
CMDSTATE[3]

**Review by kkomi-Telegram — APPROVED** [review]

**Review by kkomi-Telegram — APPROVED** [review]

**Review by kkomi-Telegram — APPROVED** [review]

**Comment by kkomi-Telegram** [comment]
advanced/index.md

**Pull request merged**
