### PR TITLE
Merge Conflict Course - Octocat edition

### PR DESCRIPTION
**Pull request by beardofedu**
## Overview
**TL;DR**
Changing the narrative of the Merge conflict course to use our Octocats. ❤️  :octocat: 

### Questions

- Are we good with the selected Octocats? Other options are all visible [here](https://octodex.github.com/)

### Next Steps

- [ ] Re-record the instructions gifs
- [ ] Ensure all non-Octocat mentions are removed
- [ ] Review exercise repository and make sure it works as intended....
- [ ] 🚢  

### Review

No @ mentions at this time.

### CODE REVIEW

**Comment by brianamarie** [comment]
@beardofedu Looked over this and I think it looks great 👍 I'm happy to be associated with the 49ers. 😄 

One nit-picky thing that has NOTHING to do with the course, and really belongs in its own PR - Instead of having 'continue' at the bottom of the IDE intro page, it would be cool to have buttons that point to each IDE. But, ignore that comment in this PR. I just wanted to be sure to write it down somewhere.

Before:
screen shot 2017-10-09 at 8 48 09 am

After: 
screen shot 2017-10-09 at 8 48 09 am

**Comment by beardofedu** [comment]
@brianamarie 

> One nit-picky thing that has NOTHING to do with the course, and really belongs in its own PR - Instead of having 'continue' at the bottom of the IDE intro page, it would be cool to have buttons that point to each IDE. But, ignore that comment in this PR. I just wanted to be sure to write it down somewhere.

UGH why did you have to have such a good idea ❤️  I think this is a great idea, are we ok with having multiple buttons at the bottom as we increase the number of GUI interfaces that we cover? 

GitKraken, Eclipse, GH Desktop, etc

**Comment by brianamarie** [comment]
> are we ok with having multiple buttons at the bottom as we increase the number of GUI interfaces that we cover?

This seems like a good question for @hectorsector or @JasonEtco - but for my eyes, I think...yes?

**Comment by brianamarie** [comment]
@beardofedu 👋 How can I help with this PR?

**Comment by beardofedu** [comment]
@brianamarie I just updated the course content and updated the course repository to include all octocat information and remove any unwanted references. The biggest thing you could do to help push this forward is to run through the class and make sure that there aren't any non-Octocat references in the activities, that the activities work, and I think we are good to go. 

I still need to update the `gifs` for the course, but that might be done by the time you try it out.

**Comment by brianamarie** [comment]
@beardofedu Could I help with the gifs? Do all of the gifs need to be re-done?

**Comment by beardofedu** [comment]
@brianamarie it is all done. let me know what you think. ❤️

**Comment by brianamarie** [comment]
@beardofedu I made a few changes
- The link users are taking and importing is under `githubtraining`, but on the first page it asked users to ask questions in the class repository on `githubschool`. I updated the `githubschool` URL to match the import URL on `githubtraining.
- When I pressed the "continue" button, it would go in a different order than the nav. I changed this so it now matches the nav.
- Added an oxford comma because I can't not 
- I removed the "continue" button for IDEs, because it only went to Atom and then back to the main IDE page. Now, there's a note saying "click in the navigation bar for specific walkthroughs". 

Please feel free to undo any of this work as always @beardofedu. This looks ready to :ship: to me!

**Pull request merged**
