### PR TITLE
I added github-git-cheat-sheet.md for tr_TR users :)

### PR DESCRIPTION
**Pull request by keramiozsoy**
## Overview

I added github-git-cheat-sheet.md for tr_TR users

**TL;DR**
<One to two sentence description of the issue you are encountering or trying to solve.>

<Link to related issue. Type `closes #RELATEDISSUENUMBER` to establish a link.>

### Questions
<If relevant, write a list of questions that you would like to discuss related to the changes that you have made.>

### Next Steps
<If incomplete, create a task list of items that are still being worked on within the Pull Request.>

### Review
Reviewer . @vigo

### CODE REVIEW

**Comment by brianamarie** [comment]
This is so great! Thank you, @keramiozsoy! 

Before we merge in translations, we usually try to get reviews from another person comfortable with the language. @keramiozsoy Do you know anyone who would be able to look at this pull request and confirm they've reviewed the translations?

**Comment by keramiozsoy** [comment]
You're welcome.
Sure , reviewer @vigo .
He will check this PR.

**Comment by vigo** [comment]
I'll check it tomorrow!

**Comment by brianamarie** [comment]
Hi @keramiozsoy! Why did you close this pull request? If you reopen it, we'll be able to get it reviewed and merged. 😊

**Pull request closed without merging**
