### PR TITLE
Add Fork Ribbon

### PR DESCRIPTION
**Pull request by beardofedu**
## Overview
**TL;DR**
Add the 'Fork me on GitHub' ribbon to the On-Demand courses.
Closes https://github.com/github/training-kit/issues/435

### Questions
- Do we want the ribbon to be on every page or just the courses?

### Next Steps
- [x] Determine if grey is our best color
- [x] Determine if left-aligned is preferred
- [x] Depending on answer to question above; insert the ribbon on other pages

### Review
cc: @crichID since you opened #435

### CODE REVIEW

**Comment by beardofedu** [comment]
Preview of the proposed implementation
image

**Comment by brianamarie** [comment]
@beardofedu ✨  ✨  ✨   

My two cents:

> Do we want the ribbon to be on every page or just the courses?

My vote: 👍  because why not? 

> Determine if grey is our best color

Ooh I think grey looks great! 

> Determine if left-aligned is preferred

I have no opinion but I think left looks fine so it doesn't interrupt the hamburger menu on the right

**Comment by crichID** [comment]
@beardofedu :tada: :heart: :tada:

> Do we want the ribbon to be on every page or just the courses?

@beardofedu my vote is for every page, but maybe that would get annoying?? I am willing to go with team consensus here. @hectorsector usually has a good eye for this kind of stuff ...

> Determine if grey is our best color

I :heart: the grey!

> Determine if left-aligned is preferred

I like that it kinda balances out the hamburger menu (and TIL what a hamburger menu is) so :+1:

**Comment by beardofedu** [comment]
- Added the banner to the homepage / training paths content.
- Added training paths to the hamburger menu

Need some 👀 to make sure it looks 👌

**Comment by brianamarie** [comment]
@beardofedu The fork-me banner looks awesome! But, I'm seeing some odd behavior with the hamburger menu. When I click it, it seems to go behind the blue banner. Do you get this behavior too? 
hamburger

**Comment by hectorsector** [comment]
> @hectorsector usually has a good eye for this kind of stuff ..

Thanks for the vote of confidence, @crichID! I think it looks great, we can always move it around when we're re-styling. 

@beardofedu I spotted two oddities:
1. When I hover over the ribbon while it's over the banner, 👍. However, when I hover over the ribbon over the white menu area, it's not a clickable link.
  fork-hover
1. On mobile size, the ribbon goes behind the menu.
  screen shot 2017-01-20 at 3 21 28 pm

**Comment by beardofedu** [comment]
@brianamarie @hectorsector 👀  to review the fix(es).

**Comment by brianamarie** [comment]
@beardofedu Tested locally and it looks ✨ 🙇 :shipit:

**Pull request merged**
