### PR TITLE
Git on Command Line On-Demand content 

### PR DESCRIPTION
**Pull request by brianamarie**
@github/services-training This PR moves content from the private on-demand repository to the training-kit. 

Please continue to test, and we can make the final improvements here. ✨ 

- [ ] Test site locally

### CODE REVIEW

**Comment by crichID** [comment]
@brianamarie @beardofedu this is looking very :sparkles:! I made some really minor edits, but I feel like this is 99.9% ready to go ... is there anything else we need to do?

**Comment by brianamarie** [comment]
@crichID ✨  😍  🌈  I think this looks so fabulous!!! 

I don't personally see anything else we need to change. @hollenberry I believe reviewed this content while it was being developed and you caught some really great things I hadn't noticed. Do you think you'll have time to do the same for this branch before we merge it in? It'll be better after we get your input. 😄

**Comment by hollenberry** [comment]
> Do you think you'll have time to do the same for this branch before we merge it in? It'll be better after we get your input. 😄

Thanks @brianamarie ! 😊 

I can add this to my calendar for first thing tomorrow. Does that work?

**Comment by hectorsector** [comment]
I'm so excited to see this take shape! Props to everyone 👏 

I've made some changes mostly from passive to active voice, and some consistency in the way we present the steps. I think this looks ready to 🚢!

**Comment by beardofedu** [comment]
So, while working on the Reset #417 course, I identified that some of the `tell me why _includes` contain content about the specific stage of the GitHub Flow the student is currently in. For the Reset course, I really just wanted the description of the 2 stage commit. 

Thoughts on pulling the Flow content from the `_include`? I think this will make it easier to share some of the content in the `_include` across courses. 

for 👀  @brianamarie @crichID @hollenberry @hectorsector

**Comment by hectorsector** [comment]
Thanks for the 👀 @hollenberry!

> Should the tell me why folder include folders for each course?

Good point, I think we should flatten the structure of `_includes`, especially since we are reusing tell-me-whys and show-me-hows across courses. But I also think that's something we can easily do later when organizing. I don't think it should stop this from 🚢ing.

Thanks for noticing the following items, I think these call for their own issues after the merge:

> Beta CSS acts like a button that can be clicked from the timeline.html, but is non responsive. Can we add hyperlinks here? Not a big deal, but if it's an easy fix.
> The minorest of nitpicks: sometimes we switch between using a . to end our steps, and other times these aren't included. This might be a good fix to toss to beginners in the open source community. I'm in favor of removing . as line endings just for added clarity when we give copy-paste commands.

**Comment by hollenberry** [comment]
> Good point, I think we should flatten the structure of _includes, especially since we are reusing tell-me-whys and show-me-hows across courses. But I also think that's something we can easily do later when organizing. I don't think it should stop this from 🚢ing.

Works for me! 👍

**Comment by hectorsector** [comment]
@beardofedu or @brianamarie wanna do the honors of pushing the big shiny green button?

**Pull request merged**
