### PR TITLE
Trimming down course descriptions

### PR DESCRIPTION
**Pull request by crichID**
Moving this PR over here from [training-web](https://github.com/github/training-web/pull/351). 

@brntbeer am I missing anything else?

### CODE REVIEW

**Comment by brntbeer** [comment]
> @brntbeer am I missing anything else?

Nothing really! just this.



Also just wanted to say that this is so great. I love how much shorter it is. I was recently playing with making the jumbo image a bit smaller (there's a lot of extra padding around it), and this definitely helps!

**Comment by crichID** [comment]
I made the minor text change recommended by @jordanmccullough

screenshot 2015-07-29 17 00 36

**Comment by jordanmccullough** [comment]
@crichID, Thanks for the edits. Let's just make one other refinement to the *GitHub for Everyone*:

> An introduction to GitHub concepts for those who prefer to use graphical tools

That keeps it two lines long, similar to the *GItHub for Developers* description. :cool::question:

**Comment by crichID** [comment]
@jordanmccullough one of the things we were hoping to mitigate was the people who show up to the "everyone" class expecting the command line. Any ideas?

**Comment by jordanmccullough** [comment]
> hoping to mitigate was the people who show up to the "everyone" class expecting the command line. Any ideas?

Ah, that's great context to have, @crichID. Thanks for the clarification.

Perhaps something like this then to highlight the GUI focus and *no* CLI:

> An introduction to GitHub for those who prefer just the web browser and  graphical clients

All just suggestions though. Go with what feels right to your :eyes:, @crichID. Thanks for permitting me to suggest and provide inputs.

**Comment by patrickmckenna** [comment]
> An introduction to GitHub for those who prefer just the web browser and graphical clients

Like that suggestion, @jordanmccullough. We should say "*Git and* GitHub," no?

**Comment by crichID** [comment]
@patrickmckenna we don't really talk about git in "everyone" other than to say "it is a version control system that GitHub is built on top of". Do you think we should still include it?

**Comment by patrickmckenna** [comment]
@crichID I defer to you, especially as the new curriculum architect.

**Comment by crichID** [comment]
Thank you everyone for your inputs. I am going to go ahead and ship this:

screenshot 2015-07-29 19 12 37

**Comment by jordanmccullough** [comment]
:sparkles: :zap: :sparkles: to everyone contributing to this. Looks great!

**Comment by loranallensmith** [comment]
This looks so good! :sparkles::sparkles::muscle:

**Pull request merged**
