### PR TITLE
German Cheat Sheet translation

### PR DESCRIPTION
**Pull request by bkimminich**
I translated the Cheat Sheet into German. Some words or sentences did not translate very well into German terms. E.g. "index" translates way easier (into "Index") than of "staging area" (into "Vorbereitungszone"?), so I used the terms that made it sound less awkward.

Maybe someone with better knowledge of "official" Git terminology in German want's to leave some comments? (e.g. authors of German Git-Books such as @esc, @Feh, @progit-de)

### CODE REVIEW

**Comment by brntbeer** [comment]
> into "Vorbereitungszone"?),

Looks like this would be "prep area" or "prep zone" which....i actually think is better than the english word "staging area".

However, looking at http://git-scm.com/book/de/v1/Git-Grundlagen-%C3%84nderungen-am-Repository-nachverfolgen, it looks like they just keep it called Staging Area. I'm guessing this is because of the terminal output? @bkimminich what are your thoughts for keeping it original.

also @bkimminich thank you so much for this translation. This is so important and I'm very excited to see Deutsch make it into our list of translated versions.

**Comment by esc** [comment]
At the time @Feh and I wrote the book, we simply germanized the English terms, i.e. branch -> der Branch, tag -> das Tag etc... I don't feel that translating technical terms like: "branch" -> "Verzweigung/Ast/Abzweig" or "cherry-pick" -> "Änderung Pflücken" is in any way conducive to understanding. Note: we did freely choose the gender of the terms based on what sounded best, since in German every Term needs to have a gender. You can check our book for examples.

**Comment by bkimminich** [comment]
@brntbeer, I think it should be fine now for a first version. I kept "Index" but put a reference to the term "staging area" into the text. But "index" seems more precise overall, even in English.

see http://www.gitguys.com/topics/whats-the-deal-with-the-git-index/

**Comment by brntbeer** [comment]
> But "index" seems more precise overall, even in English.

Yeah, thats understandable. I like the reference to staging area too! Is this good to merge now then?

**Comment by bkimminich** [comment]
I guess it'll do, or at least I don't have any better translation ideas.

**Comment by brntbeer** [comment]
> I guess it'll do, or at least I don't have any better translation ideas.

:tada: :+1: :tada: Sounds good! thank you SO much for this.

@bkimminich and @esc since you've both contributed to this PR... if you want some GitHub swag, let me know by emailing me some info and an item or two from the [shop](https://github.myshopify.com/). 

Send an email to brent@github.com and I'll see about getting things to you before the new year (no idea how long shipping takes!

**Pull request merged**
