### PR TITLE
add Persian language

### PR DESCRIPTION
**Pull request by ghaseminya**
Hi
I complete translation.

### CODE REVIEW

**Comment by stoe** [comment]
Thank you @ghaseminya.

 Could you please also add a link to `index.html`, similar to
```html
 <p><a href="downloads/de/github-git-cheat-sheet.html"><span class="octicon  octicon-cloud-download"></span> German</a></p>
```

**Comment by ghaseminya** [comment]
Hi @stoe 
where is this `index.html` file?

**Comment by stoe** [comment]
@ghaseminya, sorry for the confusion.
The `index.html` was repurposed and my earlier comment is not valid any longer.

**Comment by ghaseminya** [comment]
:octocat: :sparkling_heart:

**Comment by crichID** [comment]
@ghaseminya thank you for completing this translation! Since we do not know Persian, we would like to ask for one person who is a native speaker to complete a review of the translated text for accuracy. Do you know anyone who can complete this review?

**Comment by ghaseminya** [comment]
@crichID yes, i know,
How can i tell to him?
He is my firend, https://github.com/javadr

**Comment by crichID** [comment]
@ghaseminya the easiest way is to try mentioning him in this Pull Request or contacting him via email. @javadr would you be willing to provide a review of this translation?

**Comment by ghaseminya** [comment]
thanks @crichID

**Comment by stoe** [comment]
@ghaseminya, I used Google Chrome's translation capabilities for my review, but having a native speaker approve as @crichID suggests is even better.

image

**Comment by ghaseminya** [comment]
@stoe thanks for your idea, its good, but Persian translation in google translate is not good and perfect translation! My friend @javadr is a native Persian language and help our in this job.

**Comment by ghaseminya** [comment]
Hi @crichID 
Our translation complete, and my friend reviewed and commited some changes

**Comment by crichID** [comment]
@javadr and @ghaseminya thank you for working on this translation. I made one small change to the layout but otherwise this looks awesome!

screen shot 2017-02-28 at 11 21 42 am

I will go ahead and :ship: this with one other set of :eyes: from @github/services-training

**Comment by ghaseminya** [comment]
Thanks for @crichID and @hectorsector

**Comment by crichID** [comment]
Thank you for testing this @hectorsector - :ship:ing now

**Comment by crichID** [comment]
@ghaseminya @javadr this is now live at: https://services.github.com/on-demand/downloads/fa/github-git-cheat-sheet/

Thank you for contributing this translation of the cheat sheet.

**Comment by ghaseminya** [comment]
That's good, thanks you.
In this page:
https://services.github.com/resources/
Why didn't use original character on languages column?
For example
...
Chinese(中文)
Persian(فارسی)
...

**Comment by stoe** [comment]
@ghaseminya, that is an awesome idea. 
I suggest to add it in a separate PR.

**Comment by ghaseminya** [comment]
thanks @stoe,  thats good idea,
But i did'nt find source of this page https://services.github.com/resources/ to edit it for Persian local,

**Comment by crichID** [comment]
> But i did'nt find source of this page https://services.github.com/resources/ to edit it for Persian local

@ghaseminya yes, that page is in our services website which is a private repository. Since you provided the translation above, I will make a note to add it to that page in a future PR!

**Comment by ghaseminya** [comment]
Thanks @crichID

**Pull request merged**
