### PR TITLE
Replace ribbon with waving octocat

### PR DESCRIPTION
**Pull request by beardofedu**
## Overview
**TL;DR**
Replacing the recently added ribbon with a cute waving :octocat: .

<Link to related issue. Type `closes #RELATEDISSUENUMBER` to establish a link.>

### Questions
- Where should we identify that we are using this open source code for the ribbon now that we aren't using something GitHub created: http://tholman.com/github-corners/

### Next Steps
- Maybe create a page referencing where we get stuff like Minimal Mistakes and this ribbon

### Review
It works for me locally, so some 👀  on this might be helpful.

☮️  ❤️  & :octocat:

### CODE REVIEW

**Comment by brianamarie** [comment]
@beardofedu I made some changes to the `README.md` to call out where this awesome little waving :octocat: comes from. I also separated some of the other resources we use from where they were before. As always, please revert or edit further as you wish!

**Comment by crichID** [comment]
@beardofedu this is so insanely cute :heart:! One small thing, when I shrink the screen down to something that looks mobile sized, I get this:

screen shot 2017-02-22 at 3 33 13 pm

Thoughts?

**Comment by beardofedu** [comment]
image

**Comment by beardofedu** [comment]
@crichID I added a z-index and get the following ☝️ , I think the problem we will run into is trying to move things around based on screen size, which, can be difficult depending on how Minimal Mistakes handles responsive classes.

**Comment by crichID** [comment]
@beardofedu it looks like the behavior of the new banner mimics the behavior of the old banner so I vote we :shipit: :tada: :taco:

**Comment by hectorsector** [comment]
@beardofedu I tried to fix it, but in the process I did two BIG things:
- removed duplicate stylesheets (the entire `/_stylesheets/` directory)
- generated the stylesheets from the SCSS

This means the styles look different (not in a bad way, imo), but we need to ⚠️ thoroughly test them before merging.

**Comment by beardofedu** [comment]
I'm ✈️ tomorrow, so I will check it out.

**Comment by crichID** [comment]
> I'm ✈️ tomorrow, so I will check it out.

@beardofedu did you have a chance to test this? I can spend some time on it today if you didn't get a chance.

**Comment by beardofedu** [comment]
@crichID , I did, I actually have some notes about what needs to be addressed that I didn't post :|.

Things to Edit Based on Stylesheet Changes

# General
- Topic heading is left aligned
- Show me how / Tell me why not bold (also, font seems smaller)

# Intro to GitHub

## Edit Files

- Check to see if table was transparent letting red background show

## Celebrate

- The heart in 'We :heart: Feedback' isn't showing up

# GitHub Desktop

- Not stylesheet based, but we are inconsistently using `code blocks` and **bold** to identify clicking buttons or doing something.

**Comment by hectorsector** [comment]
If anyone needs to know how to edit SASS stylesheets, here's a primer:

1. Ensure you've got [`sass` installed](http://sass-lang.com/install).
1. Edit the SCSS file within `assets/_scss/`
1. Compile the `assets/_scss/main.scss` stylesheet which contains references to all other stylesheets using: `sass assets/_scss/main.scss assets/css/main.css`

**Comment by hectorsector** [comment]
@github/services-training has anyone had a chance to test this so I can 🚢?

**Comment by hectorsector** [comment]
Thanks for the review @beardofedu! I think I missed it earlier.

> General
>> Topic heading is left aligned

I actually think this looks good. Whattya think?


>> Show me how / Tell me why not bold (also, font seems smaller)

Agreed. Let me see if I can fix this. If I can't do it quickly, is it a deal breaker?

> Edit Files
>> Check to see if table was transparent letting red background show

Looks like it was also transparent previously.


> Celebrate
>> The heart in 'We ❤️ Feedback' isn't showing up

I see the ❤️ -- anyone else not see this? Can you confirm you still can't see this @beardofedu?

> GitHub Desktop
>> Not stylesheet based, but we are inconsistently using code blocks and bold to identify clicking buttons or doing something.

I'm not sure I understand how to fix this, @beardofedu.

**Comment by beardofedu** [comment]
> GitHub Desktop
> Not stylesheet based, but we are inconsistently using code blocks and bold to identify clicking buttons or doing something.
>I'm not sure I understand how to fix this, @beardofedu.

@hectorsector this isn't something that can be fixed via stylesheets, the course content needs to be rewritten to consistently use **bold** for a button that you click and `code blocks` for user input. It is something that is a) low hanging fruit and b) not critical for this PR

**Comment by stoe** [comment]
I love http://tholman.com/github-corners/ and am using it on http://stefan.stoelzle.me/, but does it fit with our corporate design?

Just asking?

**Comment by crichID** [comment]
@stoe great question. I am having a hard time finding a GitHub owned open source project that has the Fork me ribbon at all. I checked atom, electron, and many others. The closest thing I could find was the [opensource.guide contribute section](https://opensource.guide) (see the footer). Maybe we can ask someone in the open source repo if this has been discussed in the past?

**Comment by hectorsector** [comment]
From @crichID's thread on https://github.com/github/open-source-releases/issues/22, I think we're good to go with using GitHub Corners. If I could get one or two 👍 I can 🚢 this!

**Comment by stoe** [comment]
> removed duplicate stylesheets (the entire /_stylesheets/ directory)
> generated the stylesheets from the SCSS

@hectorsector, what is the reasoning behind deleting all the `scss` files and merging their content into an unmaintainable large `main.css` file?

**Comment by hectorsector** [comment]
@stoe there were some duplicate `scss` files, so I just removed the extra ones. I then compiled the one `main.scss` file that existed, which relies on imports of other tiny `scss` files, and produces the output under `main.css`. At least that's how I understand it -- am I missing something?

**Comment by stoe** [comment]
> Compile the a`ssets/_scss/main.scss` stylesheet which contains references to all other stylesheets using: `sass assets/_scss/main.scss assets/css/main.css`

@hectorsector, I looked at your command and think we should use the following:


|`sass -t compressed --sourcemap=none --scss assets/_scss/main.scss assets/css/main.css`

|            Command | Explanation                                                              |
|-------------------:|:-------------------------------------------------------------------------|
|    `-t compressed` | Output style. Can be nested (default), compact, compressed, or expanded. |
| `--sourcemap=none` | We don't need a sourcemap as we're not in development mode.              |
|           `--scss` | As we're using `scss` syntax not `sass` syntax.                          |

But, jekyll should do all that on it's own because of ... in `_config.yml`

```yml
sass:
  sass_dir: assets/vendor/
  style: :compressed
```

But, as we're only pointing it to `assets/vendor/` it doesn't do it for our other style files.

**Comment by hectorsector** [comment]
Thanks for reviewing this, @stoe! I've tested the command and it works, everything still looks good to me.

> But, jekyll should do all that on it's own because of ... in _config.yml

How can we go about correcting this? Should we remove `sass_dir` altogether, or point it to `assets/_scss` instead?

**Comment by stoe** [comment]
> How can we go about correcting this? Should we remove sass_dir altogether, or point it to assets/_scss instead?

I don't think we should remove ir from `_config.yml`, as some things wouldn't work then any more.

As I understand, if a resource (`css`) from within the `sass_dir` is requested by the browser, jekyll will auto-serve that content from `scss` as `css`.

Why we have manually created `css` files? I don't know.

**Comment by hectorsector** [comment]
Thanks for the explanation @stoe. 

> Why we have manually created css files? I don't know.

Changes to the `scss` aren't making their way to the rendered version of the site, they require this manual creation of `css` files. But it's good to know that it's not how it's _supposed_ to work. For now, do you (or anyone else at @github/services-training) see a reason not to 🚢 this as-is and open up a new issue to look into automated compilation of `scss` on build creation?

**Comment by crichID** [comment]
> do you (or anyone else at @github/services-training) see a reason not to 🚢 this as-is and open up a new issue to look into automated compilation of scss on build creation?

:heart: :heart: :heart: :heart: :heart: I fully support :ship:ing this change and addressing the scss as a separate PR.

**Comment by crichID** [comment]
@hectorsector I just took another peek and everything looks great. My very small comment is that I don't love the way the scenarios look here:

screen shot 2017-03-30 at 2 02 55 pm

Aside from that, this looks ready to :ship:. Thank you!

**Comment by hectorsector** [comment]
Thanks, @crichID! I toyed around with fixing that but the answer's not straightforward. I'll go ahead and merge this, and open 2 new PRs for the work that still needs to be done!

**Pull request merged**
