### PR TITLE
Create learning path file

### PR DESCRIPTION
**Pull request by beardofedu**
I originally named this file 'self-study' but based on a recommendation by @crichID I think it should be set to 'learning-path', so I need to fix that. 

I am making this PR as an opportunity to provide a list of guides and learning opportunities for newcomers to Git and GitHub. Times are based on me reading the different articles at a decent pace, so they aren't 100% accurate, but probably not off by too much.

Let me know what you think. @github/services-training  

It is currently accessed locally by adding this to the server address: `on-demand/self-study/`

### CODE REVIEW

**Comment by matthewmccullough** [comment]
I think this is a fantastic way to make our materials more approachable, clearer as to how they can be consumed based on experience, and likely to create better learning outcomes for our students.  Impressive "remix" work. ✨

**Comment by brianamarie** [comment]
@beardofedu 🙇 Thanks for jumping on this and making a deliverable so quickly!!! 

What do you think about including a subtle advert/mention of our in-person training or train the trainer? If these are going to be part of the early conversations had between sales reps and clients (as well as individual developers looking to learn), it could be a good way to introduce that. 

That being said, I have no idea where or how to best do that. Thoughts @github/services-training?

**Comment by beardofedu** [comment]
@brianamarie I like the idea of including more information of the in-person/TtT stuff. Also, I would like to integrate the quizzr placement thing you are working on. Either, as an optional response to what materials the student should study (Training Path -> Already Comfortable, Ready for the Hard(er) Stuff) or just a link to the quiz on the page itself.

**Comment by beardofedu** [comment]
This got approval. Merging.

**Pull request merged**
