### PR TITLE
[WIP] Content from Services site migration

### PR DESCRIPTION
**Pull request by JasonEtco**
Migrate a whole bunch of content from the Services website into `training-kit`.

- [x] Videos
  - [x] Add content
  - [x] Style page
- [x] Books
  - [x] Add content
  - [x] Style page
- [x] Learning Path
  - [x] Add content
  - [x] Style page
- [x] Cheat Sheets
  - [x] Add content
  - [x] Style page
- [x] Add link to Resources page from header/homepage

Each of these bits of content have to be styled properly, and linked to either from a `Resources` index (which is what existed [on the services site](https://services.github.com/resources/)) or as separate links, probably from the homepage or footer.

### CODE REVIEW

**Comment by brianamarie** [comment]
Drive by testing, and I think something's funky with the CSS for me. I'll drop a few screen shots of what I'm seeing: 
screen shot 2017-08-07 at 2 55 32 pm
screen shot 2017-08-07 at 2 55 49 pm
screen shot 2017-08-07 at 2 56 02 pm
screen shot 2017-08-07 at 2 56 18 pm

@JasonEtco Is there anything I can do to help move along this PR?

**Comment by JasonEtco** [comment]
@brianamarie - it seems thats the CSS workflow for On-Demand is borked (@hectorsector can confirm). In other words, I've made the changes but compiling the SCSS into CSS has to be done manually

**Comment by crichID** [comment]
@JasonEtco I went through and tried to test this today. Here are a few items of note:

### Linking to Resources Page

I believe we decided to replace the header links to the individual courses with a link to resources. I still see:

screen shot 2017-08-08 at 11 45 00 am
 
### Descriptions of Each Section

When I go to `on-demand/resources/` the copy for each section is currently a copy/paste. We should make each section unique.

### Styles

Per @brianamarie's comments above, I am also not seeing the styles applied as intended (I think) on the pages. I tried running `sass assets/_scss/main.scss:_site/assets/css/main.css` as recommended but got a bunch of errors as follows:

```
DEPRECATION WARNING: Passing a string to call() is deprecated and will be illegal
in Sass 4.0. Use call(get-function(“variable-exists”)) instead.
```

Not sure if this is why it is actually failing, but I am definitely not seeing the styles ☹️ 

@JasonEtco we will need to merge this PR and pull in the updated submodule before we flip the switch on the revised services site. Please let us know what we can do to help.

**Comment by JasonEtco** [comment]
> I believe we decided to replace the header links to the individual courses with a link to resources.

We had indeed decided that, and that is on my to-do list 👍 

>  I am also not seeing the styles applied as intended (I think) on the pages.

Per our Slack chat, this has been fixed and instructions have been updated in the README.

**Comment by JasonEtco** [comment]
I believe this is good to merge, pending a review 🎉  Let me know if there's anything to fix/change!

**Pull request merged**
