### PR TITLE
Update lightning video with issue changes

### LINKED ISSUE #479: Training video still referencing closed comment
## Overview
**TL;DR**
The youtube video at https://www.youtube.com/watch?v=kocHKaHtZCc is still asking briannamaries comment to be opened in the tutorial but the comment is closed and the label for it has been deleted.

#### Screenshots
<If bug fix, please upload images of the error to better showcase the problem.>

#### Reasoning
<If new idea or direction, please create a checklist of proposed ideas or next steps. [Example](https://github.com/github/training-kit/issues/415).>

### How to Contribute
- [ ] Comment on this issue if you'd like to work/collaborate on it! 
- [ ] Fork the [repository](https://github.com/github/training-kit).
- [ ] Use the [GitHub Flow](https://guides.github.com/introduction/flow/) to make changes to your fork. [This](https://services.github.com/on-demand/intro-to-github/) is a refresher course if you're unsure about how to make a change on GitHub.
- [ ] Push your changes to your repository. 
- [ ] Submit a Pull Request
  - Base Dropdown: github/training-kit
  - Compare Dropdown: Your fork

#### Testing Locally
If you'd like to make and test changes locally (and see how they would look if merged), do the following:
- In your command line:
  - [Install Git](https://git-scm.com/)
  - [Install Ruby](https://www.ruby-lang.org/en/documentation/installation/)
  - [ ] Run `script/setup`
  - [ ] Run `script/server`.
    - When successful, the script will initiate a local server at `http://127.0.0.1:4000/on-demand`.

### Questions?
- Leave a comment on this issue! Make sure to use @ mentions if you want a specific person's attention!

### PR DESCRIPTION
**Pull request by hollenberry**
## Overview
**TL;DR**
This PR updates our Lightning Video to reflect the most recent issue changes to our curriculum, as noted by a few recent community members. 

closes #479 

@github/services-training or @jameshenrylittle I'd love a review to make sure I didn't break anything unexpected. 😄 

Following a merge, I'll deprecate the old video and change permissions on YouTube.

### CODE REVIEW

**Comment by hectorsector** [comment]
Looks great @hollenberry 👍 -- is it relatively simple to normalize the audio levels? It seems to fluctuate between loud and very low for me.

**Comment by hollenberry** [comment]
> is it relatively simple to normalize the audio levels? It seems to fluctuate between loud and very low for me.

I can attempt this! Is there a specific area that seems to fluctuate more than the others that you'd recommend I focus on?

**Comment by hectorsector** [comment]
@hollenberry a good example is [around 00:40](https://youtu.be/uLmfvkxaTA8?t=41s). I did a little bit of research. If you're using Screenflow, it seems to be on the Audio inspector:

screen shot 2017-03-07 at 6 20 09 pm

**Comment by hollenberry** [comment]
How does it sound now? I think it's better, but I'm not positive.

**Comment by hollenberry** [comment]
I'll merge this to services-web after I open another quick PR.

**Comment by hollenberry** [comment]
Thank you @brianamarie and @hectorsector ! 

I really appreciate the quick feedback and quick 🚢 !

**Pull request merged**
