### PR TITLE
Add language selector per-page

### PR DESCRIPTION
**Pull request by hectorsector**
This PR allows for each page to be translated, rather than an entire course.

⚠️ This is a WIP.

### CODE REVIEW

**Comment by hectorsector** [comment]
screen shot 2017-09-15 at 5 01 14 pm

I'm not in love with the layout of these buttons, but this currently does the trick based on [this post](https://www.sylvaindurand.org/making-jekyll-multilingual/). 

Some work I want to do before shipping this:
- 🔨 down a prettier layout
- probably hide the button for the current language, only show other available languages
- consider using a Primer drop-down instead
- translate the layouts making use of existing [localization variables](https://github.com/github/training-kit/blob/master/_data/ui-text.yml).

👀 in case you're interested: @github/services-training @mberasategi @dpmex4527

**Comment by hectorsector** [comment]
Last comment for today: I've [staged](https://hectorsector.github.io/training-kit/) the current branch.

**Comment by beardofedu** [comment]
> consider using a Primer drop-down instead

I like the idea of a drop-down, we just need to make sure it is obvious for the student and not overlooked. Your current implementation is easy to find and I like it being so obvious. Hiding the current language would minimize the impact on the page and would allow use to have 4-5 translations before the drop-down might be needed.

**Comment by beardofedu** [comment]
@hectorsector the language selection tools on the Learning Path shoot way over to the right and aren't "in line" with where they are on other pages.

Example:
image

**Comment by hectorsector** [comment]
I've staged the most recent commits over at https://hectorsector.github.io/training-kit/

**Comment by hectorsector** [comment]
Next steps:
- translate the layouts making use of existing [localization variables](https://github.com/github/training-kit/blob/master/_data/ui-text.yml).
- currently, the navigation is always English, even if I'm looking at a Spanish page. The navigation should be smarter than that, and it should point to pages in the same language with which I'm currently using.

**Comment by hectorsector** [comment]
This is [ready](https://hectorsector.github.io/training-kit/) for some review! 

Could I get some eyes @github/services-training @mberasategi @dpmex4527? I can 🚢 with a couple of 👍.

**Comment by mberasategi** [comment]
I think it looks/works great. A couple of things, though:

- The "Hacer Merge de tu Pull Request" link of nav-es is wrong. My bad, I will correct when I sit in front of a computer but maybe you should do it if you plan to ship earlier.
- Index titles being in Spanish, it may be disappointing for the user to find the class in English. Maybe adding "(in English)" or "(en inglés)" to titles pending translation (in the index page) could prevent this.

**Comment by beardofedu** [comment]
@hectorsector what are you thoughts on leaving english titles for content that hasn't been translated yet? For instance, GH 102 's content hasn't been translated yet, but we translated the title which might create a disconnect (I'm clicking a link in spanish and it populates english content). 

As I was writing that suggestion I realize @mberasategi already identified that so, I guess 👍 to their thought.

**Comment by hectorsector** [comment]
Thanks for the 👀 @mberasategi & @beardofedu!

> The "Hacer Merge de tu Pull Request" link of nav-es is wrong. My bad, I will correct when I sit in front of a computer but maybe you should do it if you plan to ship earlier.

No worries, I identified it in #592, and it looks like it's being fixed in #596. I'll leave that in a separate PR and I'll test the fix against the newest changes after I merge. 

> Index titles being in Spanish, it may be disappointing for the user to find the class in English. Maybe adding "(in English)" or "(en inglés)" to titles pending translation (in the index page) could prevent this.

> what are you thoughts on leaving english titles for content that hasn't been translated yet? For instance, GH 102 's content hasn't been translated yet, but we translated the title which might create a disconnect (I'm clicking a link in spanish and it populates english content).

👍 changing that now

On a side note, I added support localizing the site title, as well. I wanted to translate the name of the site (On Demand Learning) to Spanish but I didn't want to butcher it. @mberasategi do you have a suggestion? _Entrenamiento a la Demanda_ doesn't sound right 😆 🆘  I think we'd also have to translate "Learning Path" since that page is available in Spanish.

**Comment by beardofedu** [comment]
Google Translate say Learning Path is "ruta de aprendizaje" but this translation could probably also use some of @mberasategi 👀

**Comment by hectorsector** [comment]
> "ruta de aprendizaje"

Me gusta!

**Comment by mberasategi** [comment]
"Path" would go more in the line of "itinerario", at least in the academic world. Not too fond of the "de aprendizaje" part either, let me think about it a bit. May ask my English teacher 😅

**Comment by hectorsector** [comment]
Thanks for the review, friends! I'm going to 🚢 this. We can introduce a new PR with the title changes.

**Pull request merged**
