### PR TITLE
Git Outta Trouble: Make sure all images and links work and are accessible

### PR DESCRIPTION
**Pull request by brianamarie**
… trouble course

## Overview
**TL;DR**
Git Outta Trouble: Make sure all images and links work and are accessible

Related to https://github.com/github/training-kit/issues/532

## Review

I will 🚢 with 1 👍 from @github/services-training

### CODE REVIEW

**Comment by beardofedu** [comment]
@brianamarie I'm trying to remember how the accessibility thing works, but are we trying to stay away from using sentences like this?

image

**Comment by brianamarie** [comment]
@beardofedu Good question. My understanding is that emojis are fine, as long as they're additive, not replacing words.

**Comment by beardofedu** [comment]
@brianamarie I checked the files and had Chrome read the page. 👍

**Comment by brianamarie** [comment]
@bearofedu That's a really good way to check, I never thought of that! Thanks!

**Pull request merged**
