### PR TITLE
Optimise CI build

### PR DESCRIPTION
**Pull request by stoe**
:construction: WIP :construction:

### CODE REVIEW

**Comment by stoe** [comment]
@brianamarie ^

**Comment by brianamarie** [comment]
@stoe This is awesome! It look like a lot of great changes have been made.

Is this the place to try and break it with some misspelled words? 😉

**Comment by stoe** [comment]
the big change here is to use Node `v.0.10`.
I had that 💭  when I looked at the source in https://github.com/phantompower/checkit

In the long run we might want to replace it, though.
B/c writewell's dependencies have known vulnerabilities.

image

And I also think that the issues earlier are because of memory leaks in the package that only happen when using Node JS > 4

Yes, please try and break it, @brianamarie.

**Comment by stoe** [comment]
> And I also think that the issues earlier are because of memory leaks in the package that only happen when using Node JS > 4

image

**Comment by brianamarie** [comment]
> And I also think that the issues earlier are because of memory leaks in the package that only happen when using Node JS > 4

@stoe Very insightful, good catch. 

> In the long run we might want to replace it, though.
> B/c writewell's dependencies have known vulnerabilities.

@stoe This is a good point. Sad but valid.

**Comment by stoe** [comment]
Yeay, @brianamarie.

You broke it.

**Comment by brianamarie** [comment]
> Yeay, @brianamarie.
> 
> You broke it.

Is it the spelling thing I did that broke it? The error doesn't look how I'd anticipate it to...I'm going to revert my misspell and push that up to see what changes.

**Comment by stoe** [comment]
> Is it the spelling thing I did that broke it?

Yes it is.

**Comment by brianamarie** [comment]
@stoe Hm...thoughts on the current build status?

**Comment by stoe** [comment]
> Hm...thoughts on the current build status?

@brianamarie, I think it is an issue with `writewell` not ending correctly.
I get an `exit 1` when I run `writewell -c settings.json -l script/writewell-files.txt &` locally, but it should be `exit 0` as no spelling errors are present.

**Comment by brianamarie** [comment]
> I think it is an issue with writewell not ending correctly.
> I get an exit 1 when I run writewell -c settings.json -l script/writewell-files.txt & locally, but it should be exit 0 as no spelling errors are present.

😢 I think you're right. This confuses me. I opened an issue [here](https://github.com/phantompower/checkit/issues/6) yesterday to get an outside opinion. Got the response, but I'm having trouble making sense of it: 

>I would say that is a permission issue.  You might install from NPM?
https://www.npmjs.com/package/writewell

@stoe Do you think at this point, troubleshooting writewell is the best path forward, or should we look into another tool?

**Comment by stoe** [comment]
> Do you think at this point, troubleshooting writewell is the best path forward, or should we look into another tool?

I'm not sue it's worth the effort.
The tools seems pretty wonky to me.

**Comment by brianamarie** [comment]
> I'm not sue it's worth the effort.
> The tools seems pretty wonky to me.

Closing this PR, and setting a reminder for myself in 3 months to circle back to the concept.

**Pull request closed without merging**
