### PR TITLE
Create consistent logo and fix stylesheets

### PR DESCRIPTION
**Pull request by hectorsector**
The stylesheets for Cheatsheets was broken after #478 was merged in. This PR addresses that fix, and also closes https://github.com/github/services-web/issues/697 and closes https://github.com/github/training-kit/issues/497.

Need a few 👀 please @jordanmccullough @github/services-training

### CODE REVIEW

**Comment by brianamarie** [comment]
@hectorsector 🤔 Something isn't adding up quite right for me locally.  I did run `script/bootstrap` and `script/build`, could I be missing another step? 
screen shot 2017-04-05 at 6 59 32 am

**Comment by hectorsector** [comment]
@brianamarie interesting, only think I can imagine is that it's caching an old style? Can you try a different browser, or a hard refresh? Is that what you're seeing after `script/server`?

This is what I see:

screen shot 2017-04-05 at 10 59 54 am

**Comment by brianamarie** [comment]
😢 

test-broken-link

**Comment by hectorsector** [comment]
Hm... @brianamarie, I'm not sure what's going on. @hollenberry checked and he's [able to see it](https://github.slack.com/archives/C0F4LK0KX/p1491499886102425). I'm still wondering whether it's a style cache -- can you try it on a different browser or in incognito?

@jordanmccullough @github/services-training has anyone else had trouble with this?

**Comment by jordanmccullough** [comment]
Looks good locally for me....

image

**Comment by jordanmccullough** [comment]
It looks like the footer might not be styled though:

image

**Comment by hectorsector** [comment]
Thanks @jordanmccullough -- it wasn't styled before either. Since it's pretty important that we 🚢 a fix to the style, and it's been confirmed by you, @hollenberry, and myself, I'll go ahead and merge this as-is. I'll open a new issue for the styled footer, as well.

**Pull request merged**
