### PR TITLE
[WIP] Design refactor using Primer

### PR DESCRIPTION
**Pull request by JasonEtco**
## Design Refactor

Following the redesign of our [services site](https://services.github.com), we want to update the visuals of On-Demand to align more closely to the GitHub brand and visual language, along with cleaning up some markup and making it easier for us to build new things on it.

**Important Note:** The goal of this PR is not to _change_ On-Demand's organizational structure, or make content adjustments. It is purely for visual and code-style changes.

## Primer

Going forward, we'll be using [Primer](https://github.com/primer/primer-css) as a replacement for our existing Jekyll theme. Primer is the GitHub CSS Toolkit and will empower us to build a GitHub-esque product quickly and comfortably.

## To-Do

- [x] Refactor _includes (eliminate unnecessary file, cleanup markup)
- [x] Cleanup _layouts
- [x] Replace existing theme with Primer styles
  - [x] Homepage timeline
  - [x] `simple-class.html`
  - [x] Resources
  - [x] Community
- [ ] Verify that all courses still look normal

### CODE REVIEW

**Comment by JasonEtco** [comment]
@github/services-training - I'm thinking of refactoring some of the JS (mostly for performance and code-clarity reasons); do you think that should be a separate PR? If so, then this PR is ready to test 🎉

**Comment by hectorsector** [comment]
Looks great so far @JasonEtco! It looks like we lost the submenu from the Git Out of Trouble section, which just happens to be one of my tasks for cleanup this week :trollface: I've got the beginning of adding them in locally, but will probably need some help styling it to look like a proper submenu. What do you think?

**Comment by JasonEtco** [comment]
Thanks for bringing that up @hectorsector - it's been fixed now (since 31e33f2)

**Comment by hectorsector** [comment]
I don't think this is related to the Primer refactoring, but these links in GitHub for Windows Users are broken ( 👀 @beardofedu )

screen shot 2017-08-25 at 10 08 07 am

**Comment by JasonEtco** [comment]
> I don't think this is related to the Primer refactoring, but these links in GitHub for Windows Users are broken

Good catch @hectorsector - I (or @beardofedu if he's so inclined) will fix them in a separate PR, because yeah it is in fact not due to the Primer integration.

**Comment by beardofedu** [comment]
@JasonEtco / @hectorsector this has been added to the items on the GitHub for Windows course review (https://github.com/github/training-kit/issues/573) and will be resolved.

**Pull request merged**
