### PR TITLE
rename cn to zh_CN

### PR DESCRIPTION
**Pull request by PeterDaveHello**
cc @hectorsector

### CODE REVIEW

**Comment by hectorsector** [comment]
Thanks for the PR, @PeterDaveHello! And thanks for volunteering to start a translation to Traditional Chinese ❤️ 

Pinging some :octocat:s that might also be willing to help with the translation: @sophiec @hohsiangwu @muan.

**Comment by muan** [comment]
@PeterDaveHello fyi @JuanitoFatas had a 99% finished version previously, but I dropped the ball completely... :pray::sob: https://github.com/muan/training-kit/pull/1

**Comment by PeterDaveHello** [comment]
Oops, since it's closed and there is no Traditional Chinese on the website so I didn't notice that there was one, any suggestion how we should do guys? 😄

**Comment by muan** [comment]
@PeterDaveHello have you started on anything? if it's already plenty then perhaps just carry on, and maybe that old PR discussion has something useful to you. If not then I can reopen that PR and we can update from that branch?

**Comment by PeterDaveHello** [comment]
@muan yes I have started, based on the English and `zh_CN` (origin `cn`) translation, I believe that the old PR discussion will be useful for me, so maybe I'll try to compare the two versions first 😃

**Pull request merged**
