### PR TITLE
Removed usage of "either" in list of file states.

### PR DESCRIPTION
**Pull request by tedmcox**
I removed the word "either" in the list of file states. I believe either should be used when only two options are available.

### CODE REVIEW

**Comment by brntbeer** [comment]
I personally think this is a fine addition. @github/training-teachers thoughts?

**Comment by patrickmckenna** [comment]
:+1: Thanks, @tedmcox.

**Comment by jaw6** [comment]
:+1: Looks good to me!

**Comment by loranallensmith** [comment]
:+1: :sparkles:

**Pull request merged**
