### PR TITLE
Miscellaneous fixes in the Spanish version of 'github-foundations.md'

### PR DESCRIPTION
**Pull request by andres-mancera**
Hi @matthewmccullough : I have taken care of a few minor issues that I had mentioned [here](https://github.com/github/training-kit/issues/308) a couple of days ago.  Please let me know if you have any questions.  Cheers!

### CODE REVIEW

**Comment by matthewmccullough** [comment]
Thank you, @andres-mancera !

**Comment by andres-mancera** [comment]
@matthewmccullough : I noticed that Spanish translations are only available for [github-foundations.md](https://github.com/github/training-kit/blob/master/workbooks/es/github-foundations.md) and [github-intermediate.md](https://github.com/github/training-kit/blob/master/workbooks/es/github-intermediate.md).  Is there any reason for this?  Are there some other documents that you would like me to translate?

**Comment by matthewmccullough** [comment]
@andres-mancera Your help is most appreciated! Definitely the advanced one would be useful as well.  I think our five core offerings to translate are:

* [Foundations Class Curriculum](https://github.com/github/training-kit/tree/master/foundations)
* [Intermediate  Class Curriculum](https://github.com/github/training-kit/tree/master/intermediate)
* [Advanced  Class Curriculum](https://github.com/github/training-kit/tree/master/advanced)
* [Git Cheatsheet](https://github.com/github/training-kit/tree/master/downloads)
* [Subversion Migration Cheatsheet](https://github.com/github/training-kit/tree/master/downloads)

**Comment by andres-mancera** [comment]
@matthewmccullough : Why do you have 2 separate folders for Spanish documents under [Git Cheatsheet](https://github.com/github/training-kit/tree/master/downloads)?  All other languages have both the *.md and the *.pdf files in the same directory.  For Spanish, you have a [es](https://github.com/github/training-kit/tree/master/downloads/es) folder with the pdf file and a [es_ES](https://github.com/github/training-kit/tree/master/downloads/es_ES) folder with the md file.  Should I start by moving everything under only one folder?

**Comment by matthewmccullough** [comment]
@andres-mancera We did have (or anticipated having) two or more flavors of Spanish since we serve the [Mexico and Spain communities](https://github.com/github/training-kit/pull/133#issuecomment-44811895).  We used the ISO [language an country code](https://github.com/github/training-kit/issues/65#issuecomment-39902296).

**Comment by andres-mancera** [comment]
Thanks for the explanation @matthewmccullough .  Perhaps @antonio can chime in and explain the reason why he felt you needed to differentiate between Spanish from Spain and from the rest of the countries?  IMHO, we can and shout carry out these translations in _"universal Spanish"_, in the sense that most (if not all) Spanish speakers around the world should be able to understand them.  I think that is what we should aim for.  BTW - I am a native Spanish speaker from South America.

**Comment by antonio** [comment]
Hola @andres-mancera !

> Perhaps @antonio can chime in and explain the reason why he felt you needed to differentiate between Spanish from Spain and from the rest of the countries?

Absolutely. When I had a look at the original version, it read very odd to me, and I thought my version would probably read the same way to the person that had written the original one, so we ended up with the two versions. I'm all :+1: on having a universal document, would you like to help me with that?

**Comment by andres-mancera** [comment]
Hola @antonio !  I'll be glad to help you out.  Where/how do we get started?  :smile:

**Comment by jordanmccullough** [comment]
> Where/how do we get started?

Thanks for offering to assist, @andres-mancera. If you'd like to contribute, here are the steps:

1. Fork the [`training-kit/`](https://github.com/github/training-kit) repository
2. Create a branch, edit, and commit your changes
3. Open a [Pull Request](https://help.github.com/articles/using-pull-requests/) with your contributions
4. Watch for a [merge](https://help.github.com/articles/merging-a-pull-request/) of your changes
5. Enjoy your [contribution graph](https://help.github.com/articles/viewing-contributions-on-your-profile-page/) lighting up

:smile:

**Comment by antonio** [comment]
@andres-mancera please ping me in the pull requests and I'll highlight the parts that read odd to me. For instance, in the changeset of this PR "por algunas investigaciones" does not feel right, but "según algunas investigaciones" does. Would that still be good for you?

**Pull request merged**
