### PR TITLE
Fix broken links

### PR DESCRIPTION
**Pull request by mateusortiz**
## Overview
**TL;DR**

Fix some broken links on the Spanish version.

`closes` issue #592

### CODE REVIEW

**Comment by hectorsector** [comment]
Wohoo! 🎉 Thanks for the fix @mateusortiz!

**Comment by hectorsector** [comment]
Just a quick note, I've merged this but you won't see it live yet until it's deployed to services.github.com. I'll do that in a bit!

**Comment by mateusortiz** [comment]
Thanks @hectorsector 👏

**Comment by hectorsector** [comment]
It's live now!

**Pull request merged**
