### PR TITLE
use json 1.8.2

### PR DESCRIPTION
**Pull request by halfaro1**
I had some problems building the training kit and they seemed due to json 1.8.1. I was able to correct it by using json 1.8.2, and this PR aims to make that change to the kit.

@brianamarie since you tested this for me earlier, could you test out this branch?

@github/services-training and @patrickmckenna: am I on the right track there? Is there a justification for json 1.8.1?

Here's some of the errors I was getting from running `_buildscripts/bootstrap`:
```
An error occurred while installing json (1.8.1), and Bundler cannot continue.
Make sure that `gem install json -v '1.8.1'` succeeds before bundling.
```

And when running `gem install json -v '1.8.1'`:
```
Building native extensions.  This could take a while...
ERROR:  Error installing json:
	ERROR: Failed to build gem native extension.

    current directory: /usr/local/lib/ruby/gems/2.3.0/gems/json-1.8.1/ext/json/ext/generator
/usr/local/opt/ruby/bin/ruby -r ./siteconf20160512-54192-1q7rjtq.rb extconf.rb
creating Makefile

current directory: /usr/local/lib/ruby/gems/2.3.0/gems/json-1.8.1/ext/json/ext/generator
make "DESTDIR=" clean

current directory: /usr/local/lib/ruby/gems/2.3.0/gems/json-1.8.1/ext/json/ext/generator
make "DESTDIR="
compiling generator.c
In file included from generator.c:1:
./../fbuffer/fbuffer.h:175:47: error: too few arguments provided to function-like macro invocation
    VALUE result = rb_str_new(FBUFFER_PAIR(fb));
                                              ^
/usr/local/Cellar/ruby/2.3.1/include/ruby-2.3.0/ruby/intern.h:797:9: note: macro 'rb_str_new' defined here
#define rb_str_new(str, len) __extension__ (    \
        ^
In file included from generator.c:1:
./../fbuffer/fbuffer.h:175:11: warning: incompatible pointer to integer conversion initializing 'VALUE' (aka 'unsigned long') with an expression of type 'VALUE (const char *, long)' (aka 'unsigned long (const char *, long)') [-Wint-conversion]
    VALUE result = rb_str_new(FBUFFER_PAIR(fb));
          ^        ~~~~~~~~~~
1 warning and 1 error generated.
make: *** [generator.o] Error 1

make failed, exit code 2

Gem files will remain installed in /usr/local/lib/ruby/gems/2.3.0/gems/json-1.8.1 for inspection.
Results logged to /usr/local/lib/ruby/gems/2.3.0/extensions/x86_64-darwin-15/2.3.0/json-1.8.1/gem_make.out
```

### CODE REVIEW

**Comment by halfaro1** [comment]
And I just realized I wrote `jason` instead of `json` in my commit message, bah!

**Comment by patrickmckenna** [comment]
@halfaro1 I'm getting the same results as you (errors for `1.8.1` that are fixed by this PR).

**Comment by stoe** [comment]
Only getting the error if I don't use Ruby 2.0.0 as also set in the
script/cibuild file.

-- 

*Stefan Stölzle <https://de.linkedin.com/in/stefanstoelzle>*
Services Engineer
Github, Inc.
https://github.com | https://services.github.com

**Comment by brianamarie** [comment]
> Here's some of the errors I was getting from running `_buildscripts/bootstrap`:

@halfaro1 I'm no longer getting errors for this! 🎉 


> And when running `gem install json -v '1.8.1'`:

I'm still getting the same errors you pasted in the original post. 

Thank you @halfaro1 for looking into this! ✨

**Comment by halfaro1** [comment]
I'm closing this PR as it seems I wasn't using the right version of ruby as @stoe suggested.

**Pull request closed without merging**
