### PR TITLE
Replace video

### PR DESCRIPTION
**Pull request by hollenberry**
Following up on #412 , I've updated the video to remove the issues steps, as well as the "STEP BLANKS" transitions.

Looking for a quick 👍 or two from @github/services-training on the changes 😄

### CODE REVIEW

**Comment by brianamarie** [comment]
@hollenberry This could be just because of my internet connection, but some of the images are pretty fuzzy. Is anyone else seeing this? 

screen shot 2016-12-21 at 3 29 48 pm


Also, there's a slight drop in audio at 2:17 but I don't know if that's a blocker. 

Thank you for opening the PR and re-editing to get this updated! 👍

**Comment by hollenberry** [comment]
@brianamarie Awesome, thank you for watching! 

I think that the quality is due to your internet, as I'm not seeing the same. However, that audio dip is definitely a thing. I wonder if I can easily equalize.

**Comment by crichID** [comment]
> This could be just because of my internet connection, but some of the images are pretty fuzzy. Is anyone else seeing this?

@brianamarie it looked ok in mine but it was playing in HD mode! I'm not sure if there is anything we can do about the compression since YouTube does this automagically - but maybe @loranallensmith  can give us a hint?

**Comment by hollenberry** [comment]
> compression since YouTube does this automagically - but maybe @loranallensmith can give us a hint?

@crichID I believe @loranallensmith is OOO for the holidays, but I followed [this](https://github.com/github/training-video/blob/master/docs/guides/training-video-production-guide.md) resource for the best practices in exporting/uploading.

**Comment by crichID** [comment]
@hollenberry I think this video looks :sparkles: in HD but agree it could use a little tweaking for people viewing it in a lower resolution. However, I don't think this should prevent us from shipping this iteration as it will be an awesome resource for our learners. I am going to go ahead and merge this in so I can update the course on services.github.com!

Perhaps after the holidays we could spend some time with @loranallensmith or @pamboat for guidance on tweaks that will make this even better!

**Pull request merged**
