### PR TITLE
Corrected some grammatical and spacing issues.

### PR DESCRIPTION
**Pull request by halfaro1**
Corrected some spacing and grammatical issues for the spanish cheat sheet. We were alerted to these issues via email.

/cc: @github/training-teachers

### CODE REVIEW

**Comment by brntbeer** [comment]
cc @Arturoytal, this may be relevant to your interest =)

**Comment by halfaro1** [comment]
@github/training-teachers could you 👀 this PR and 👍 ? I know it's in Spanish but I'd like to make sure formatting and such looks consistent before merging.

**Comment by brianamarie** [comment]
@halfaro1 My Spanish skills are limited to bossing around little kids, so I'm afraid I can't help with that, but the formatting and everything else looks great to me! 👍 Unless someone would like to get another Spanish speaker to look at this, which seems like overkill for such a small edit, my vote is to :shipit: 🎉

**Comment by brntbeer** [comment]
@halfaro1 lets wait until @arturoytal or some spanish speaking member of GH can read this?

cc @CarmenPalMar @antonio @raviolicode @bitoiu @rubiojr  @vmg: can someone take a look at the updated PDF and just give it a quick look over and see if it looks okay? See here: https://github.com/github/training-kit/blob/correct-es/downloads/es_ES/github-git-cheat-sheet.pdf

**Comment by bitoiu** [comment]
> My Spanish skills are limited to bossing around little kids, so I'm afraid I can't help with that, but the formatting and everything else looks great to me!

The same applies to me :smile:

**Comment by arturoytal** [comment]
Hello!
It looks fine!

Thanks!

**Comment by CarmenPalMar** [comment]
@brntbeer I have to admit to me the Spanish doesn't sound very natural. I'd be happy to help a bit more in the written aspect. It sounds to me a bit too literally translated. 
@antonio @miguelff @rubiojr @vmg what do you think?

**Comment by brntbeer** [comment]
> I'd be happy to help a bit more in the written aspect. It sounds to me a bit too literally translated.

@CarmenPalMar that's good perspective, maybe we could suggest or work together on some changes to the markdown files in another pull request and then update the PDF with it. That is of course to say, if others think we should make the changes now, maybe we'll do it now! 😄

**Comment by miguelff** [comment]
> @brntbeer hellooo, think it's awesome that you're getting involved. Buut I have to admit that to me the Spanish sounds a bit off. I'd be happy to help a bit more in the written aspect. It sounds to me a bit too literally translated. 

It reads pretty artificial to me as well.  Nevertheless, what could sound unfamiliar to us Spaniards, can feel natural in other Spanish-speaking countries and vice-virsa, as we use different expressions.

As tactical solution, I'd suggest to use the same terms that are currently applied in the Spanish translation of Pro Git https://git-scm.com/book/es/v2. What do you think?

cc @rocio for her opinion on this

**Comment by brntbeer** [comment]
> As tactical solution, I'd suggest to use the same terms that are currently applied in the Spanish translation of Pro Git https://git-scm.com/book/es/v2. What do you think?

That would be the best course of action in my mind too @miguelff

**Comment by rocio** [comment]
> It reads pretty artificial to me as well. Nevertheless, what could sound unfamiliar to us Spaniards, can feel natural in other Spanish-speaking countries and vice-virsa, as we use different expressions.

I got the same impression, however, I'm not used to read technical books/documentation in Spanish, TIL about https://git-scm.com/book/es/v2 it could be that too, but one thing I did notice is that just by reading *"Nombres del archivo de refactorizacion"* for example, doesn't ring a bell even if I know what we are talking about.

**Comment by halfaro1** [comment]
Hi folks! I agree that much of the document seemed literally translated to me. However, I 👍 moving forward with the better translation via a separate PR and recommend merging this one just to correct the blaring grammatical issues.

**Comment by crichID** [comment]
@halfaro1 :+1: to keeping this small change moving forward and doing the larger change as a different PR!

**Comment by brntbeer** [comment]
> However, I 👍 moving forward with the better translation via a separate PR and recommend merging this one just to correct the blaring grammatical issues.

totes @halfaro1

**Pull request merged**
