### PR TITLE
Update GitHub 101

### LINKED ISSUE #568: Reviewing GitHub 101
## Overview
**TL;DR**

Reviewing the GitHub 101 and identifying any new features, bug fixes, or general items that need eyes or a refresh.

- [x] References to Continue button should be written with a capital C to be consistent with button look / feel (Introduction to GitHub page)
- [x] Standardize **bolding** in content
- [x] Select the `Unlimited public repositories for free.` option. (Create a GitHub Account)
- [x] `awesome photo and a fun bio.` Change photo to profile picture. (Link to Help doc https://help.github.com/articles/setting-your-profile-picture/)
- [x] Change the wording for Step 2. (Join the Class Repository)
- [ ] gif is inaccurate due to new template (Join the Class Repository)
   - [ ] all gifs are inaccurate because they show Pulse / Graphs
- [x] Change `Navigate to the Code tab to find the README.` to include `repository README` or something (Explore the GitHub Repository)
- [x] Pulse and Graphs are referenced without the correct UI context (inside Insights) (Explore the GitHub repository)
- [x] Use GitHub Flow doesn't really have steps, seems to be an introduction to GH Flow and might be able to be moved to Create a Branch
- [x] Create a Branch needs bolding stuff
- [x] gif doesn't use the site that is linked for Manually Search (Find Your Coordinates) https://mynasadata.larc.nasa.gov/latitudelongitude-finder/
- [x] button text is Create pull request, (Create a Pull Request)
- [x] Reference 404 error, but that should be limited to the GitHub Pages courses and not this one. Opportunity to identify some of the common reasons a build fails. (Edit Files on GitHub)
- [x] Issue with image in Tell Me Why _Merge visual_ (Merge Your Pull Request)
- [x] Modify end para / Add `heart` to the We :heart: Feedback title (You Completed the GitHub Flow)

### PR DESCRIPTION
**Pull request by beardofedu**
## Overview
**TL;DR**
This pull request makes a number of small changes to GitHub 101 including but not limited to:

- Standardizing bolding
- Updating content based on UI changes
- Fix an issue where an image wasn't loading
- I added a period at the end of a numbered step, it was glorious

Closes #568 

### Review
Currently not ready for 👀 , at mentions to come. ❤️

### CODE REVIEW

**Comment by beardofedu** [comment]
Ok @github/services-training I think I'm ready for some eyes on this content. 👀 

### Discussion Topic

I have not updated the gifs yet, the UI might have changed, but the interactions within the gifs are still correct. So as part of clean-up week, do we want to create new gifs or wait until the instructions they are showing off through the magic of moving pictures are incorrect?

**Comment by brianamarie** [comment]
Looks good! Checking it out locally, I really like the bolding. 😻 

> do we want to create new gifs or wait until the instructions they are showing off through the magic of moving pictures are incorrect?

@beardofedu My personal opinion is that a slightly different UI is okay. As long as the instructions are the same, and the UI is close enough (which I believe it is) I think it's fine.

I do think we should consider moving the gifs to the top instead of in the "show me how" but that's a totally different topic.

**Comment by beardofedu** [comment]
@brianamarie moved the gifs. if you can check that is works for you that would be ✨

**Comment by brianamarie** [comment]
@beardofedu 🎉 Looks great to me!

**Comment by beardofedu** [comment]
Merging this because @brianamarie said I could.

**Pull request merged**
