### PR TITLE
Change wrong ticks on line 44 to grave accent

### PR DESCRIPTION
**Pull request by vyablonskyy**
Wrong ticks on line 44 "Enter: 'git status'." which results in showing `git status` not in code formatting. Should be grave accent ( `` )

### CODE REVIEW

**Comment by brianamarie** [comment]
@vyablonskyy Thank you for these changes - you're right! cc/ @beardofedu since he completed this content originally.  Are there any other changes you want to make in this PR @vyablonskyy? If not, I think it looks ready to ship! 👍

**Comment by vyablonskyy** [comment]
@brianamarie not other changes from my side for now. Thanks.

**Comment by beardofedu** [comment]
@vyablonskyy Thank you so much for your contribution and your keen 👀  😄 . 

Looks good to me @brianamarie , good to 🚢

**Comment by brianamarie** [comment]
Woohoo! I'm going to merge now. Thank you for contributing, @vyablonskyy! 🎉

**Pull request merged**
