### PR TITLE
Add support for multiple languages

### PR DESCRIPTION
**Pull request by hectorsector**
This PR is prompted by the amazing work done in #586 (🙇 @mberasategi). The goal here is to find a good starting point for localizing the On-Demand site. 

🚧 WIP but any ✋ are welcome!

### CODE REVIEW

**Comment by hectorsector** [comment]
I think this is ready to 🚢. It's not the most elegant solution, but it's a start. Once we get this merged, I'd like to implement a localization solution that's more robust, and can show [translated versions of any page](https://www.sylvaindurand.org/making-jekyll-multilingual/), not just specific courses.

For now, could I please get some 👀 on this? You can see the published version that's [staged on my fork](https://hectorsector.github.io/training-kit/) if you don't want to build locally.

**Comment by beardofedu** [comment]
@hectorsector thoughts on not having the language specified if we just have one? Also thoughts on adding padding above the language selection buttons?

image

**Comment by crichID** [comment]
> thoughts on not having the language specified if we just have one? Also thoughts on adding padding above the language selection buttons?

:+1: on both of these from me!

**Comment by JasonEtco** [comment]
In the future, it could use a dropdown with an `onchange` handler to redirect to the relevant page/language. The button solution definitely works with just two languages though!

>  thoughts on adding padding above the language selection buttons?

+1 from me too 💖

**Comment by mberasategi** [comment]
Thanks @hectorsector ! And sorry everyone for the irrelevant commits :see_no_evil: I think it's a great simple way to have localizations available to users, +1 to padding.

Maybe another option could be, because course titles will still link to the English version, to add something like "This course is also available in `language1`, `language2` and `language3`." when there are translations. It's basically the same though.

**Comment by hectorsector** [comment]
Thanks for the reviews @beardofedu @crichID @JasonEtco @mberasategi! Added your suggestions, and shipping!

**Pull request merged**
