### PR TITLE
Update github-git-cheat-sheet.md

### PR DESCRIPTION
**Pull request by mxui**
1. little correction: Github -> GitHub
2. adjustment of markdown headings hierarchy

### CODE REVIEW

**Comment by patrickmckenna** [comment]
@mxui Thanks for offering these edits. We certainly want to incorporate the spelling fixes:

> 1. little correction: Github -> GitHub

However, for consistency with the [English version](https://github.com/github/training-kit/blob/e303de7cfb0ad4c18fc077e1b67313b5ed8ffec2/downloads/github-git-cheat-sheet.md), we probably want to keep only the sample commands in fenced code blocks, like this:


screen shot 2015-12-21 at 9 27 15 am


rather than including the command explanations in there, too:


screen shot 2015-12-21 at 9 27 30 am


Would you mind updating this PR to make that adjustment?

/cc @github/training-teachers

**Comment by mxui** [comment]
@patrickmckenna Okay,I understand.

**Comment by patrickmckenna** [comment]
> Configure user information for all local repositories is the summary of the following commands and should be highlighted to distinguish.

@mxui That's a good point, as is your suggestion to have a PDF version available for each translation.

@jordanmccullough Are we using a Markdown-to-PDF tool to generate each PDF, or do we have some other process?

**Comment by jordanmccullough** [comment]
> @jordanmccullough Are we using a Markdown-to-PDF tool to generate each PDF, or do we have some other process?

@patrickmckenna, Given the custom layout of the Adobe Illustrator file, the process has been mapping (i.e. copy/paste) the content from Markdown to `.ai` for the current time.

**Comment by brntbeer** [comment]
> Configure user information for all local repositories is the summary of the following commands and should be highlighted to distinguish.

@mxui i totally agree. Because of consistency with the rest of the translations, i think we should keep it as is now.

In a future pull request, we can add better highlighting to those mini section headers like you suggested.

**Pull request closed without merging**
