### PR TITLE
Change baseurl to actual url when its in links

### PR DESCRIPTION
**Pull request by brianamarie**
## Overview
**TL;DR**
I'm not sure if this was changed to `base-url` on purpose or by accident. In case it was an accident, this pull request will change the hard-coded links to be the correct links. 

They still function with `base-url` but it seems difficult to read as a code maintainer, and I think for contributors it makes more sense in these links to have the entire URL. 

### Questions
@hectorsector @github/services-training  Were these changes made on purpose?

### CODE REVIEW

**Comment by hollenberry** [comment]
@brianamarie Looks like these were all batched in with this commit: https://github.com/github/training-kit/commit/71c2210e35b9e56fa9675f4bb18a3b48c6abf5d3

@JasonEtco do you remember why we did that?

**Comment by JasonEtco** [comment]
Hrm, I don't know why really. Generally, they shouldn't need to have the `https://services.github.com` part at all and should work like:

```
[here is my link](/on-demand/link-to-thing)
```

As for the `{{ site.baseurl }}`, I'm generally a fan of using variables whenever possible but it doesn't _reaaaallly_ matter, so long as we never ever change the `baseurl` (which could totally happen)

**Comment by brianamarie** [comment]
@JasonEtco Would it make sense to change it to [{{site.baseurl}}/link]?

**Comment by hollenberry** [comment]
@JasonEtco friendly bump on this one 👍 

> Would it make sense to change it to [{{site.baseurl}}/link]?

**Comment by JasonEtco** [comment]
Whoops don't know how this one flew by me. I think the answer is yes, we should change them all to have `{{ site.baseurl }}/path/to/file` whenever possible.

**Comment by hectorsector** [comment]
Apologies, this confusion is probably my fault! I'll copy 🍝 something I was chatting with @hollenberry about in #581:

> {{ site.baseurl }} is a variable in Jekyll that tells most of our pages to use /on-demand/ as part of their links. This is preferrable over direct links to on-demand because it will preserve link functionality should we ever change the paths around.

> A while ago, I did a find-and-replace-all direct mentions of /on-demand/ with the more proper {{ site.baseurl }} but, in so doing, I realized I mistakenly replaced some mentions of /on-demand/ that Jekyll cannot see.

**Comment by crichID** [comment]
> I realized I mistakenly replaced some mentions of /on-demand/ that Jekyll cannot see.

Perhaps this would be a good instruction to call out in the contributing guide @hectorsector -- especially for users who are planning to customize the training and use it on their own instance.

**Comment by hectorsector** [comment]
> Perhaps this would be a good instruction to call out in the contributing guide @hectorsector -- especially for users who are planning to customize the training and use it on their own instance.

https://github.com/github/training-kit/pull/571/commits/15286e494d46cf78f1555602ba1a4931b2a05f7d what do you think, @crichID?

**Pull request merged**
