### PR TITLE
Add Joyride

### PR DESCRIPTION
**Pull request by beardofedu**
Working on adding an instructional overlay to the On Demand content using [Joyride](http://zurb.com/playground/jquery-joyride-feature-tour-plugin).

Things to identify:
- [ ] How to include the `<ol>` element Joyride needs
- [ ]  Add `id`s to the relevant objects within the page
- [ ]  Add button / script to load the tour

@hectorsector, pinging you as you know the backend of On Demand much better than I.

Relevant PR: #412

### CODE REVIEW

**Comment by brianamarie** [comment]
@beardofedu For background, is this to fulfill the checkbox ✔️ for [the introduction to GitHub re-formatting](https://github.com/github/training-kit/pull/412) by adding overlay with tips?

**Comment by beardofedu** [comment]
@brianamarie Yea, I just need to figure out how to implement the `id`s by looking at the templates being used to convert the MD files into HTML files.

**Comment by hectorsector** [comment]
@beardofedu I think I got it to work, although it's not pretty! But hopefully it removes a blocker that can help you get it started.

Since the sections that are called out in Joyride are parts of `simple-class.html`, only courses that use that layout will work -- so far the GitHub Desktop course works 👍 

screen shot 2016-12-20 at 2 04 38 pm

**Comment by beardofedu** [comment]
Don't think we need to pursue this change. Closing it for now.

**Pull request closed without merging**
