### PR TITLE
Fix the markdown header in subversion migration section.

### PR DESCRIPTION
**Pull request by IonicaBizau**
📝 

Here is why:

screen shot 2016-09-02 at 18 49 49

### CODE REVIEW

**Comment by crichID** [comment]
@IonicaBizau thank you for contributing this change! :ship:ing it now.

**Comment by IonicaBizau** [comment]
@crichID You're welcome! I'm not sure how/when the content is updated on the live site, but looking at the [page](https://services.github.com/kit/downloads/subversion-migration.html), the issue is still there. Was the HTML been rebuilt?

**Comment by brntbeer** [comment]
> I'm not sure how/when the content is updated on the live site, but looking at the page, the issue is still there. Was the HTML been rebuilt?

@IonicaBizau sorry about that! that's because this repo is a submodule of another repo that controls all of services.github.com. Once we send a PR to update the submodule, it'll go live! I'll push that forward for Monday. 👍

**Comment by IonicaBizau** [comment]
@brntbeer Sounds good! 👍 Thanks! 🍰

**Pull request merged**
