### PR TITLE
Update GitHub pages gem

### PR DESCRIPTION
**Pull request by mattdavis0351**
update gem file to match what we see in docs

### CODE REVIEW

**Review by hectorsector — APPROVED** [review]
@mattdavis0351 I think with this change we're good to go. CI failed but I don't know that it was a true fail -- feel free to merge if you think it's good!

**Comment by mattdavis0351** [comment]
@hectorsector is this even needed?  This was a part of the troubleshooting I was doing, but if you're PR is building just fine then we can probably discard this one

**Comment by hectorsector** [comment]
I think it's a good idea to bump the pages gem. Doesn't break anything and the site is building in preview.

**Comment by mattdavis0351** [comment]
@hectorsector the error on CI is `document tree depth exceeded`.  Placing this here in case we need to chase down errors later.  The preview seems to be building appropriately.

I'll merge this so I look cool 😉

**Pull request merged**
