### PR TITLE
switch formatting for two column git translation

### PR DESCRIPTION
**Pull request by brntbeer**
Hate such a big commit, but because of div tags being spread out on the new formatting, i took the approach of just one single commit.
screen shot 2015-08-26 at 4 04 07 pm

cc @github/training-teachers for some feedback. We'll also need to incorporate this into training-web afterwards.

### CODE REVIEW

**Comment by patrickmckenna** [comment]
@brntbeer With the caveat that I know nothing about web design, a few thoughts:
- can we balance out the links to diff translations, so each column has a roughy equal number?
- Alignment looks odd? Left side headers indented by unequal amounts. Is the right side column supposed to look like a sidebar? Also, Git, SVN header sizes look equal to Community, Social headers.

**Comment by brntbeer** [comment]
> Alignment looks odd? Left side headers indented by unequal amounts. Is the right side column supposed to look like a sidebar? 

yeah, that's just an issue of the fact that i'm doing this change with `col-md-*` type of css elements, which all have some sort of padding on them.

> Also, Git, SVN header sizes look equal to Community, Social headers.

Yeah, i can drop git and SVN header sizes down a notch.

> can we balance out the links to diff translations, so each column has a roughy equal number?

I could, but i wanted it to be a bit more like a longer list. Eventually we'll have to find a better way to list these.

**Comment by patrickmckenna** [comment]
> I could, but i wanted it to be a bit more like a longer list. Eventually we'll have to find a better way to list these

Got it. Can we make this a single list for now then? Or does that screw up formatting in another way?

**Comment by brntbeer** [comment]
@patrickmckenna a single column isn't going to fix the padding that's on the css elements, if that's what you mean

**Comment by patrickmckenna** [comment]
@brntbeer I meant a single column for the list of all cheat sheet translations, so the Italian link doesn't stand by itself. Presumably that would let us fit "Brazilian Portuguese" on a single line, too?

**Comment by brntbeer** [comment]
Made it two columns, and removed padding.


screen shot 2015-08-27 at 5 40 29 pm

**Comment by brntbeer** [comment]
@patrickmckenna sorry, once last time before I merge, does :arrow_up: look good?

**Comment by patrickmckenna** [comment]
@brntbeer :shipit:

**Pull request merged**
