### PR TITLE
Brazillian portuguese sheet link

### PR DESCRIPTION
**Pull request by brntbeer**
The sheet was missing a few things, including the column break down that i should have caught previously.

### CODE REVIEW

**Comment by brntbeer** [comment]
Wanted to cc @shana and @felipedau since you've both worked in this realm.

I've kept the `pt` section, so we can keep that translation (I believe this was a concern as mentioned here: https://github.com/github/training-kit/pull/328#issuecomment-126795227).

I've also renamed the directory to be more appropriate and named `pt_BR`

Thoughts?

**Comment by brntbeer** [comment]
also cc @loranallensmith since this effects some upstream changes we're looking at. Once this gets merged in we can take care of other works we are doing to make this reflected on the page itself.

**Comment by loranallensmith** [comment]
@brntbeer I'm running everything locally and it looks good to me as far as structure goes.  :+1: 

br-pt

**Comment by felipedau** [comment]
> Wanted to cc @shana and @felipedau since you've both worked in this realm.

Thanks!

> Thoughts?

I believe everything is good with the Brazilian cheat sheet.

I would say that the pt-PT link could be hidden until the cheat sheet is done, because the current PDF is just another version of the pt-BR. If there is already a pt-PT branch somewhere then just ignore what I said :P

**Comment by shana** [comment]
@brntbeer Thanks for doing this, this is awesome!

> I would say that the pt-PT link could be hidden until the cheat sheet is done, because the current PDF is just another version of the pt-BR. If there is already a pt-PT branch somewhere then just ignore what I said :P

Hiding the link until it's done is a good idea, it's better to do that than have the two be the same (that will likely make people complain). I started working on it but haven't finished because [insert need more hours of the day complaint here]. I'll invest some more hours in it and do a PR based on this one :smile: 

In a completely unrelated note, have you thought about having a booklet git cheat sheet like the one we have for the GitHub flow? The small format of the GitHub flow booklet makes it very easy to carry around, it's very popular in the booths I've manned.

**Comment by xantage** [comment]
welcome

**Comment by brntbeer** [comment]
> I would say that the pt-PT link could be hidden until the cheat sheet is done, because the current PDF is just another version of the pt-BR. If there is already a pt-PT branch somewhere then just ignore what I said :P

My apologies, I actually didn't notice that the `.pdf` version of the cheat sheet was the version of pt_BR before @felipedau updated it a few months ago (https://github.com/github/training-kit/pull/328) and because of a comment in another repo prompting me to make this PR. @felipedau @shana I'll revert the move of the pdf to a `pt/` folder and fix some things around. @shana a PR on eventually adding a pt_PT translation would be :zap: :zap: :zap: :gem: :gem: :gem: 

I'm guessing it's best to just render the `.html` for the Brazilian translation? Since that's the most updated version of this, that seems to be best.

**Comment by loranallensmith** [comment]
@brntbeer looks like that pt_PT link removal is :+1: for me locally here.  And the pt_BR link goes to the `.html` cheatsheet in pt_BR.  :sparkles:

screen shot 2015-10-08 at 8 20 10 pm

**Comment by felipedau** [comment]
> I'm guessing it's best to just render the .html for the Brazilian translation? Since that's the most updated version of this, that seems to be best.

I really like the `html` layout, I am just wondering if people would expect something to download (because the website says `available for download...`) such as a `pdf`. Maybe all of the cheat sheets could be in `html` and then have a download button somewhere to save a `pdf` in case they really want to have it?

> @brntbeer looks like that pt_PT link removal is :+1: for me locally here. And the pt_BR link goes to the .html cheatsheet in pt_BR. :sparkles:

It also looks good here :)

**Comment by brntbeer** [comment]
@felipedau understandable, unfortunately we don't have someone to continuously turn these `.html`s into pdfs to keep them updated (If I knew how to do that, I'd do it. May look into alternatives like .pdf style sheets).

Thanks all for the review!

**Comment by felipedau** [comment]
> @felipedau understandable, unfortunately we don't have someone to continuously turn these .htmls into pdfs to keep them updated (If I knew how to do that, I'd do it. May look into alternatives like .pdf style sheets).

Oh, that's right. I remember you said that.

> Thanks all for the review!

Thank **you**.

**Pull request merged**
