### PR TITLE
Add clarity around instructions for creating issue instead of commenting

### PR DESCRIPTION
**Pull request by brianamarie**
## Overview
**TL;DR**
This PR 
- adds clarity around instructions where users are asked to create an issue instead of comment on an issue
- removes the step for managing notifications since users won't be getting blasted with emails

## Review
This should be ready for review. Since it's a small change, I'd like to 🚢 with 1 or 2 👍 from @github/services-training.

### CODE REVIEW

**Comment by hectorsector** [comment]
@brianamarie just made a few small tweaks to use our favorite mood. Everything else looks ✨

**Comment by r5atom** [comment]
@brianamarie I see you've removed _page 03_. Can I have a go make the instructions so that users silence their own issue?

**Comment by beardofedu** [comment]
@r5atom 

I think adding the instructions for managing notifications would be a great addition to the course. I definitely support you working on the content. Can you try and create it as an "include" for a "Tell Me Why" section?

cc: @brianamarie

**Comment by r5atom** [comment]
@beardofedu Do you mean I can create a file [_\_includes/tell-me-why_](https://github.com/github/training-kit/tree/master/_includes/tell-me-why)/_manage-notifications.md_ ?

**Comment by beardofedu** [comment]
@r5atom 

Yes, you will need to create the _includes/tell-me-why file and then include it in one of the course Tell Me Why sections. If you encounter issues, give me an @ mention.

**Pull request merged**
