### PR TITLE
Added Greek Translation

### PR DESCRIPTION
**Pull request by gvasilakiss**

### CODE REVIEW

**Comment by brianamarie** [comment]
Hi @gvasilakiss, thank you for opening this PR! 

I am going to convert this to a "draft" pull request, because it is not yet ready for review. Once you're ready for review, please feel free to convert it out of draft mode.

Also, before we merge this in, we will ask that another fluent Greek speaker reviews this pull request. If you are able to help us find that reviewer, that will help us merge this PR sooner. 😊

**Comment by gvasilakiss** [comment]
Finished Greek Translation and added file to index.html

**Review by MikeStavr — APPROVED** [review]
I reviewed the translation and they are translated correctly according the Greek language

**Review by gfilippa — APPROVED** [review]
I reviewed the translation and they are translated correctly according the **Greek** language

**Comment by brianamarie** [comment]
Awesome. Thank you so much, @gvasilakiss, @MikeStavr, and @gfilippa! ✨

**Pull request merged**
