### PR TITLE
Show subversion link

### PR DESCRIPTION
**Pull request by brntbeer**
:warning: WIP :warning: 

We've had https://training.github.com/kit/downloads/subversion-migration.html for a hot minute now. This will add the pdf download onto the site.

## TODO

~~- [ ] Create actual PDF asset (cc @jordanmccullough ?)~~ No need to have pdf

### CODE REVIEW

**Comment by brntbeer** [comment]
Actual image of how this would look:

screen shot 2015-02-23 at 1 42 02 pm

**Comment by jordanmccullough** [comment]
> Create actual PDF asset (cc @jordanmccullough ?)

Given the level of effort involved in producing the PDF, recent intention has been to ship all the documents via web page. The pages are all dark-shipped at this point, but publicly available.

**Git Cheat Sheet**
- https://training.github.com/kit/downloads/github-git-cheat-sheet

**Subversion to Git Migration**
- https://training.github.com/kit/downloads/subversion-migration

**Comment by brntbeer** [comment]
Impossibly old, but i noticed this commit existed in #317 so i wanted to ship this beforehand. 

I'll give it a day or two but then merge these two commits

**Comment by brntbeer** [comment]
ping @github/training-teachers. Does the above snapshot of this change look okay/

**Comment by matthewmccullough** [comment]
:+1:

**Comment by brntbeer** [comment]
Thanks all!

**Comment by loranallensmith** [comment]
:+1: here as well!

**Pull request merged**
