### PR TITLE
Added Italian translation

### PR DESCRIPTION
**Pull request by lcafaro**

### CODE REVIEW

**Comment by brntbeer** [comment]
@lcafaro thanks for the contribution!

I'll have to make some additional edits to make the italian link preview on the kit's homepage, which would look something like this:

screen shot 2015-08-24 at 11 37 36 am

But i think this is good for now! I don't know anyone else who can preview this work and double check translations though. So i'll continue to find someone quickly just for some peer review, but may just merge it anyways

**Comment by lcafaro** [comment]
No problem!
I've asked a friend of mine to peer review the content for me and he'll report back soon.

**Comment by jacopofar** [comment]
Hello,
I checked the content of the pull request and I confirm the translation is correct.

**Comment by brntbeer** [comment]
Looks good to me! thanks @lcafaro and @jacopofar !!

**Pull request merged**
