### PR TITLE
Fix leading path in cheat sheets so html will render properly

### PR DESCRIPTION
**Pull request by crichID**
This PR fixes a bug found in #427 with the rendering of the html cheat sheets. 

Will :ship: with 1 :+1:.

### CODE REVIEW

**Comment by brianamarie** [comment]
@crichID I'd love to test this locally - but I think the instructions in the `README.md` are mostly to serve the on-demand content.  How can I try to check this locally so that I can give you a 👍 ?

**Comment by crichID** [comment]
> How can I try to check this locally so that I can give you a 👍 ?

@brianamarie great question! We should probably add this to the instructions somewhere, but in the meantime, here they are:

1. Run `script/server`
2. Access the desired cheat sheet at `http://127.0.0.1:4000/on-demand/downloads/<language>/<cheat-sheet-title>/`. An example would be: `http://127.0.0.1:4000/on-demand/downloads/fr/git-github-cheat-sheet/`

**Comment by brianamarie** [comment]
@crichID Thank you for sharing the directions. I agree, we should document those somewhere. 

I'm trying to follow them but it's not serving properly. Once I get the server running from this branch and navigate to `http://127.0.0.1:4000/on-demand/downloads/de/git-github-cheat-sheet`, I only see:

```
Not Found

/on-demand/downloads/de/git-github-cheat-sheet not found.
```

Is there a step I'm missing?

**Comment by crichID** [comment]
@brianamarie sorry, I mis-typed the cheat-sheet title, it should be `http://127.0.0.1:4000/on-demand/downloads/de/github-git-cheat-sheet/`

**Comment by brianamarie** [comment]
Ah! Well that works beautifully! 👍

**Pull request merged**
