### PR TITLE
Translate Git cheat sheet to Polish

### PR DESCRIPTION
**Pull request by krysti500**
## Overview
**TL;DR**
Added basic translation to Polish.

### CODE REVIEW

**Comment by brianamarie** [comment]
Hello @krysti500! Thank you for this contribution. Typically, when we have community contributions for translations, we like to get them reviewed by another person fluent in that language before we merge it in. Do you happen to know anyone that speaks and writes Polish on GitHub that would be able to review this pull request? I'll ask around internally at GitHub and see if there is anyone there that could review, too. 

Thanks again!

**Comment by paluchnuggets** [comment]
I am Polish  and if that is ok I can review it :)

**Comment by brianamarie** [comment]
> I am Polish and if that is ok I can review it :)

That would be great, thank you @paluchnuggets!

**Comment by brianamarie** [comment]
Awesome, thank you so much @krysti500 and @paluchnuggets! 🎉

**Pull request merged**
