### PR TITLE
Foundation chapter summaries

### PR DESCRIPTION
**Pull request by jordanmccullough**
Initiated by discussions in https://github.com/github/training-kit/issues/258, the Kit content can benefit from several "summary" components:

- Section/chapter overview in one to two sentences
- Class overview of all content objectives as opening slide

### CODE REVIEW

**Comment by jordanmccullough** [comment]
Added support for class-level "checklist" as discussed [here](https://github.com/github/training-kit/issues/258#issuecomment-60952005). Thanks @matthewmccullough for the suggestion!

kit-checklist-in-action

**Comment by jordanmccullough** [comment]
@github/training-teachers, Would :heart: getting your :eyes: on this and merging in at the earliest possible. The chapter summaries are first-draft stages, so please feel free to adjust and commit directly to this PR's [branch](https://github.com/github/training-kit/tree/slide-chapter-summaries) if you have any tuning.

**Comment by brntbeer** [comment]
I love these section overviews, as well as the checklist at the top (it works with the `teacher` param too!)

One thing I had originally wanted was an overview of what specifically would be covered in each class. This seems to be covered in the **Feature Overview** sections of each chapter, but I didnt know if we had any plans for shortening up each overview and put it on a single page maybe on https://training.github.com/kit or something.

Really loving the overview, the checklist, and sub-titles of chapter headings though and think this is good to go regardless of above comment.

**Comment by jordanmccullough** [comment]
>  shortening up each overview and put it on a single page maybe on https://training.github.com/kit or something.

I'm :+1: on this idea and aggregating each of these "overviews". Subsequent PRs we could script a "slurp" to build the single page slide of all summaries. Is this similar to what you're envisioning?

**Comment by matthewmccullough** [comment]
@jordanmccullough:

* I'm happy to contribute a tiny bit by updating the `training-web` site with the latest kit
* Is it appropriate (I know you now track major releases of `kit` with a tracking issue and pre-planned release version) to tag `training-kit` with this awesome new feature and content?

**Comment by jordanmccullough** [comment]
@matthewmccullough, Release [cut and noted](https://github.com/github/training-kit/releases/tag/1.8.0) when it shipped yesterday. :wink:

**Comment by matthewmccullough** [comment]
@jordanmccullough :metal: Just tried it out on the public https://training.github.com/kit site

**Review by Scutua — APPROVED** [review]

**Pull request merged**
