### PR TITLE
Edit

### PR DESCRIPTION
**Pull request by keangkai**
i think read easier than and add missing semicolon somewhere

## Overview
**TL;DR**
<One to two sentence description of the issue you are encountering or trying to solve.>

<Link to related issue. Type `closes #RELATEDISSUENUMBER` to establish a link.>

### Questions
<If relevant, write a list of questions that you would like to discuss related to the changes that you have made.>

### Next Steps
<If incomplete, create a task list of items that are still being worked on within the Pull Request.>

### Review
<If complete, or ready for :eyes:, use @mentions for quick questions, specific feedback, and progress updates.>

### CODE REVIEW

**Comment by paipai111** [comment]
[SQL_Server_Migration_to_the_Cloud_Offer_Datasheet.pdf [SHARED].pdf](https://github.com/github/training-kit/files/1464008/SQL_Server_Migration_to_the_Cloud_Offer_Datasheet.pdf.SHARED.pdf)

**Comment by paipai111** [comment]
recover messages

**Comment by brianamarie** [comment]
Hi @keangkai! As you can see, this file is within the `node_modules`. This mean that this file isn't actually one we maintain, but a dependency. 

Based on the [npm page](https://www.npmjs.com/package/primer-navigation), I think the code is [maintained here](https://github.com/primer/primer/tree/master/modules/primer-navigation). Thank you for helping us keep our code in order, but I think that it's best to close this pull request. Maybe Primer would be the best place for this pull request. 😄  If you see anything to improve in our code that isn't a module, please open another pull request. We love contributions! ❤️

**Comment by keangkai** [comment]
Thank you

**Comment by paipai111** [comment]
av class="menu" aria-label="Person settings">
  <a class="menu-item selected" href="#url" aria-current="page">Account</a>
  <a class="menu-item" href="#url">Profile</a>
  <a class="menu-item" href="#url">Emails</a>
  <a class="menu-item" href="#url">Notifications</a>
</nav>

**Pull request closed without merging**
