### PR TITLE
Translate site and learning path title to Spanish

### LINKED ISSUE #583: Translation of Learning Path to Spanish
## Overview
**TL;DR**
<One to two sentence description of the issue you are encountering or trying to solve.>
I'm thinking os translating the [Learning Path](https://services.github.com/on-demand/resources/learning-path/) into Spanish, but have some doubts on how to do it.

#### Reasoning

I decided to start working with Github with my Communication Degree students this fall semester. They are complete newbies and learning to become journalists, so not into the developer profile at all. It is going to require me preparing very basic materials to introduce version control, git, Github, Markdown, and even plain-text editing I'm afraid. So I just thought that if they could have this transalated _in situ_ instead of given by me through some of our school platforms, it will be more convenient for them, it could work as a demonstration on how to collaborate and of course anyone else reading Spanish could take advantage.

My questions are,

1. which are the files that need to be edited, and
1. what naming convention should I use for translated files?

Regarding the first question, I see the learning path index is in `https://github.com/github/training-kit/blob/master/resources/learning-path/index.html` but actual path files are in `https://github.com/github/training-kit/tree/master/paths`. Not sure if that's all or I am missing something. 

And about the second, I've seen the debate on naming conventions but can only find them in `downloads`, so not sure if that is the rule also for everything else.  Should I create `paths/es_ES` and have everything translated there? Or `paths/intro-to-github/es_ES` (and `resources/learning-path/es_ES` for the index)?

Also, I'm not sure about how this would be available on the interface for users, or if translations of the site are planned at all. So let me know!

### PR DESCRIPTION
**Pull request by hectorsector**
This PR translates the site title (_On Demand Training_ ➡️ _Aprende a tu ritmo_) and the title of _Learning Path_ ➡️ _Ruta de aprendizaje_. It closes #583.

I can 🚢 with one 👀 from @dpmex4527, @mberasategi, or any other Spanish speakers (maybe @bescalante?) willing to take a quick peek that can help rate my translation.

### CODE REVIEW

**Comment by mberasategi** [comment]
_Learning Path ➡️ Itinerario de aprendizaje_ sound more natural to me, but it's just an opinion!

**Comment by bescalante** [comment]
I'm wondering if @alebourne can take a quick 👀  - she's my go to for translated docs!

**Comment by alebourne** [comment]
Hi @bescalante 
I'll have a look.

**Comment by hectorsector** [comment]
Thanks for the 👀 and 👍 @dpmex4527 @mberasategi @bescalante @alebourne ❤️

**Pull request merged**
