### PR TITLE
Slovak Github Git Cheat Sheet

### PR DESCRIPTION
**Pull request by marekdlugos**
This is a Slovak translation of Git Cheat Sheet from Github that you can find on [Github Resources page](https://services.github.com/resources/).

Slovak language is also very similar to Czech what means that now it's accessible to over **15 million Slovak & Czech people**.

I hope that I followed all the rules for contribution correctly and believe that it's ready for merge.

### CODE REVIEW

**Comment by brntbeer** [comment]
@marekdlugos this is great!! I'm looking to get some additional people to review this. I will of course double check the formatting though

**Comment by marekdlugos** [comment]
@brntbeer Thanks mate! I'll ping few of my mates from Slovakia to take a look on that, too.

Cc @petertoth @jsuchal

**Comment by crichID** [comment]
@marekdlugos thank you SO much for translating this! I am looking forward to getting at least 1 review completed so we can :shipit:

**Comment by petertoth** [comment]
Looks good to me!

**Comment by jermenkoo** [comment]
Looks good to me!

**Comment by marekdlugos** [comment]
@brntbeer Done. 🎉

**Comment by crichID** [comment]
@marekdlugos This looks awesome! I am going to go ahead a :ship: this now!

**Pull request merged**
