### PR TITLE
[WIP] General Design Improvements

### PR DESCRIPTION
**Pull request by JasonEtco**
Following the work done in #567 (Replacing the Jekyll theme with Primer), its now a lot easier for us to make design improvements that align with the GitHub visual language, look awesome and are easy to maintain. This PR will change some things 🎉 

- [x] Main site header
- [x] Page heroes
  * Typography tweaks
  * Add graphics to spice things up ([code-lines](https://assets-cdn.github.com/images/modules/site/heroes/simple-codelines.svg) and/or [confetti](https://resources.github.com/assets/img/layout/background_articles.png))
- [ ] Timeline
- [x] Refactor contribution graph CSS

### CODE REVIEW

**Comment by JasonEtco** [comment]
As of the first commit, here's what the site-header looks like:

image

**Comment by beardofedu** [comment]
I don't know how I feel about the blue on blue, it kind of looks like when the CSS was created we didn't use the correct shade of blue ... I know the goal is to make out website more inline with a traditional GitHub website, but I don't know if the blue on blue is a design choice I'm a fan of ... but I'm not a designer, so, there are probably studies and data to support this design decision.

**Comment by JasonEtco** [comment]
Thanks @beardofedu, I appreciate the feedback. I personally like the dark-blue against the lighter blue hero, I find it sets the site apart from other GitHub properties.

Here's the same image with a light header, similar to what we have going on [the Services site](https://services.github.com). I find the contrast of the light header against the blue hero to be a little jarring; on pages where the hero is light its great though.

image

We could also go for something like [opensource.guide](https://opensource.guide) (big squishy buttons) but we would have to reduce the amount of links we have right now for it to look right.

**Comment by brianamarie** [comment]
@JasonEtco I'm not a huge fan of the blue on blue, but I see what you mean about the blue alone being kind of jarring. Could we change the shade of blue? Or, make the top match .com by being dark?
 
screen shot 2017-08-30 at 12 53 27 pm

**Comment by JasonEtco** [comment]
@brianamarie I've tried the dark header, I'm hesitant to use it here. I don't want it to be too "github.com"; it should feel like a separate entity, plus the blue/gray combo isn't very nice. Below I've made the blue darker and tweaked some spacing things, let me know what you think 💖 

image

And even darker:

image

The darker-est:

image

---

Note: I think of these, the top is the best but I've shared them here anyway.

**Comment by brianamarie** [comment]
@jasonetco 😍 I agree completely. Thank you!

**Comment by beardofedu** [comment]
@JasonEtco I tried to test this locally, and I'm not seeing the changed color bar across the top, did that get scrapped, or does my local build just hate me?

**Comment by hollenberry** [comment]
@JasonEtco I really like the last 3 images that you presented. I definitely agree that the original blue/blue felt off, but with shades it looks pretty excellent. 

Personally, I like the middle one, best.

**Comment by JasonEtco** [comment]
I added this sticky footer (will always either be at the bottom of the page or below all the content, never hovering weirdly), see `After:Before`:

image

**Comment by JasonEtco** [comment]
image

image

**Comment by crichID** [comment]
:heart: these look great @JasonEtco! The white header always felt a little unfinished to me, so this makes me happy 🌮 🌮 🌮

**Comment by beardofedu** [comment]
@JasonEtco  I really ❤️ the dark blue on the grey hero, so maybe we need to change the hero of the home page / courses, but I'm not going to stop it from 🚢 ing because I don't support a dark blue bar.

**Comment by JasonEtco** [comment]
Thanks for the feedback folks.

I.. um... I can't merge because I don't have `write access`... Would one of you please merge this in while I go sob in a corner?

**Comment by hollenberry** [comment]
Oops! Sorry for the team ping, was experimenting with the 2.11 team request video.

**Pull request merged**
