### PR TITLE
Change courses to include GitHub Pages reference in title

### PR DESCRIPTION
**Pull request by beardofedu**
## Overview
**TL;DR**

As GitHub Pages is a frequently searched term, I've modified the course title to include GitHub Pages and the specific interface used to interact with Git and GitHub. 

### Questions

- Do people think this change looks 👍 ?

### Next Steps

- [x] Quick run through of the internal contents of the class to make sure the course title isn't referenced. 

### Review

I will ping once I have given the content a quick once over.

### CODE REVIEW

**Comment by beardofedu** [comment]
So apparently I had this PR already open, so I am going to kill 2 birds with 1 stone and complete both of these so it can be shipped together.

**Comment by beardofedu** [comment]
@crichID are you good with me merging this?

**Comment by crichID** [comment]
> @crichID are you good with me merging this?

Ummm, yes? :wink: Thank you for making these updates @beardofedu

**Comment by genSud** [comment]
Предлагаю помочь мне разработать программу для сбора статистики грамотности каждого участника передачи информации в любом виде, обсудим?

**Pull request merged**
