### PR TITLE
Fix Arabic translation header based on #561

### PR DESCRIPTION
**Pull request by wisn**
## Overview
**TL;DR**
As I've reported on #561, the Arabic translation header now RTL aligned.

screenshot from 2017-08-23 00-57-05

Since RTL aligned remove the bottom padding, I use `<br>`.

### CODE REVIEW

**Comment by brianamarie** [comment]
@wisn This looks great to me, it looks exactly like the screen shot when I spin it up locally. Thank you! 

I will merge this PR now, but this may not show until later when we update the parent site.

Thank you again for your contribution! 🎉 ❤️ :octocat:

**Comment by wisn** [comment]
@brianamarie Ah you're right. The description going out from the `p` tag. Change the `<div dir="rtl">` to `<p dir="rtl">` and remove `<br>&nbsp;` should fix it. 😃

**Comment by brianamarie** [comment]
@wisn I'm not sure I understand - it looked fine to me locally. Do we need to make [these most recent suggestions](https://github.com/github/training-kit/pull/563#issuecomment-324113152) for it to be displayed correctly?

**Comment by wisn** [comment]
@brianamarie When we are using a smaller screen the header will looks like this.

screenshot from 2017-08-23 01-37-02

The most recent suggestion is a perfect solution.

screenshot from 2017-08-23 01-38-56

**Pull request merged**
